import { COMPANY } from "@/content/company";

/**
 * The site's legal documents, in all three languages.
 *
 * Written for this business specifically: we buy cars at Korean auction/dealer level, quote
 * one landed price, ship them by sea and deliver to the buyer's address. The documents say
 * exactly that, and nothing they cannot back up. They are a starting point drafted in good
 * faith, NOT legal advice — the owner should have a Bulgarian lawyer review them before
 * relying on them commercially, which the pages themselves say.
 */
const UPDATED = "2026-06-08";

const doc = (title, intro, sections, updated = UPDATED) => ({
  title, intro, sections, updated,
});

// The owner's own privacy policy, as their lawyer settled it. Version and date come from that
// document rather than from UPDATED, so a change to another page cannot silently restamp it.
const PRIVACY_STAMP = {
  bg: "Версия 1.1 · Актуализирана на 6 август 2026 г.",
  ro: "Versiunea 1.1 · Actualizată la 6 august 2026",
  en: "Version 1.1 · Updated 6 August 2026",
};

// Built on demand rather than at import time: the company details can be edited in the
// admin, and these documents quote them.
function build() {

const BG = {
  terms: doc(
    "Общи условия",
    `Тези условия уреждат използването на ${COMPANY.site} и поръчката на автомобил чрез ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
    [
      ["Какво правим",
        [`Показваме автомобили, обявени за продажба в Южна Корея, преведени на български, румънски и английски.`,
         `Цената, която виждаш, е крайна прогнозна цена до твоя адрес: включва автомобила, морския транспорт, мито и ДДС, освен ако на страницата на обявата не е посочено друго.`]],
      ["Обявите не са наша собственост",
        [`Данните и снимките идват от корейския пазар и се обновяват периодично. Възможно е автомобил да бъде продаден или свален от продажба, преди да получим обновени данни.`,
         `Затова обява на сайта е покана за запитване, а не обвързваща оферта. Обвързваща цена получаваш в писмено потвърждение от нас.`]],
      ["Поръчка и плащане",
        [`След запитване потвърждаваме наличността, окончателната цена и срока, и издаваме документ за плащане. Договорът се счита сключен, когато потвърдим поръчката писмено.`,
         `Плащането се извършва по банков път към ${COMPANY.name}. Не приемаме плащания в брой за автомобили.`]],
      ["Срокове и доставка",
        [`Ориентировъчният срок от потвърдена поръчка до доставка е между 6 и 10 седмици и зависи от корабните разписания, пристанищните и митническите процедури.`,
         `Датите в раздел „Проследи автомобила“ са прогнозни. Последната стъпка — доставка до твоя адрес — се изчислява като приблизително седем дни след пристигане в европейското пристанище.`]],
      ["Състояние на автомобила",
        [`Автомобилите са употребявани. Показваме инспекционния доклад и историята, доколкото са налични от източника.`,
         `Употребяван автомобил може да има износване, което не е отразено в документите. При съмнение поискай допълнителна проверка преди да поръчаш.`]],
      ["Право на отказ",
        [`Ако си потребител по смисъла на българското законодателство, имаш законовите си права, включително право на отказ, когато то е приложимо за конкретната сделка.`,
         `Автомобил, поръчан и внесен по твоя изрична индивидуална заявка, може да попада в изключенията от правото на отказ. Ще ти посочим кое важи за твоята поръчка, преди да платиш.`]],
      ["Отговорност",
        [`Не отговаряме за забави, причинени от превозвачи, пристанища, митници или органи, извън нашия контрол, но те винаги ти се съобщават веднага щом ги узнаем.`,
         `Не отговаряме за косвени вреди, като пропуснати ползи или разходи за наем на друг автомобил.`]],
      ["Спорове",
        [`Прилага се българското право. Спорове се решават от компетентния български съд, освен ако задължителна потребителска норма не предвижда друго.`,
         `Можеш да се обърнеш и към Комисията за защита на потребителите или към платформата за онлайн решаване на спорове на Европейската комисия.`]],
      ["Контакт",
        [`Пиши ни на ${COMPANY.email}. Отговаряме в рамките на два работни дни.`]],
    ]
  ),
  privacy: doc(
    "Политика за поверителност",
    `${COMPANY.name}, ЕИК ${COMPANY.eik}, със седалище и адрес на управление ${COMPANY.address}, е администратор на личните данни, обработвани през ${COMPANY.site}. Тази политика обяснява какви данни събираме, на какво основание, откъде ги получаваме, с кого ги споделяме, колко дълго ги пазим и как упражняваш правата си по Общия регламент (ЕС) 2016/679 (GDPR) и Закона за защита на личните данни.`,
    [
      ["1. Кой отговаря за данните ти",
        [`Администратор: ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
         `Адрес: ${COMPANY.address}.`,
         `Контакт за въпроси и заявки по GDPR: ${COMPANY.email}; тел. ${COMPANY.phone}.`,
         `Не сме длъжни да определяме длъжностно лице по защита на данните и не сме определили такова. Заявките се обработват от управителя и получаваш отговор до един месец от получаването им. При сложни или многобройни заявки срокът може да се удължи с още два месеца, като ще те уведомим за удължаването и причините в рамките на първия месец.`]],
      ["2. Какви данни обработваме",
        [`Профил: имейл, име (ако го попълниш), парола — съхранявана само като необратим хеш (Argon2id) — и данни за двуфакторна защита или passkey, ако си я включил.`,
         `Доставка и фактуриране: име, улица, град, пощенски код, държава и телефон — само ако ги въведеш.`,
         `Запитвания и кореспонденция: съобщението, имейлът и телефонът, които ни изпращаш, и отговорите ни.`,
         `Плащания и депозити: сума, статус, дата и идентификатор на плащането. Данните на картата ти се въвеждат директно при Stripe — ние никога не виждаме и не съхраняваме номер на карта.`,
         `Пратки: номера на товарителници и контейнери, свързани с твоята поръчка, събитията от превозвача и държавата за последната стъпка от доставката.`,
         `Технически данни: IP адрес, тип браузър и устройство, време на заявката и записи за вход/изход от профила (включително списък на активните сесии, който виждаш в профила си).`,
         `Запис за съгласието ти: кои категории бисквитки си приел или отказал, кога и срещу коя версия на политиката.`,
         `Предпочитания (само със съгласие): кои марки, модели и горива разглеждаш, в бисквитка на твоето устройство със срок 90 дни.`]],
      ["3. Откъде получаваме данните",
        [`Повечето данни получаваме директно от теб. В някои случаи получаваме данни, свързани с теб, и от трети страни:`,
         `от превозвача и услугата за проследяване на контейнери — събития по пратката, статус на контейнера и товарителницата;`,
         `от Google — имейл, име и профилна снимка, само ако избереш вход с Google;`,
         `от Stripe — резултата, статуса и идентификатора на плащането ти (но не и данните на картата);`,
         `от нашите логистични, митнически и корейски партньори — данни, необходими за конкретната ти поръчка и превоз.`,
         `Категориите на тези данни и правните основания за обработването им са същите като описаните в тази политика.`]],
      ["4. Задължителност на предоставянето на данните",
        [`Предоставянето на част от данните е необходимо, за да сключим и изпълним договора с теб или за да спазим закона:`,
         `без имейл и парола не можем да създадем и поддържаме профил;`,
         `без име, адрес и телефон не можем да обработим поръчка, внос и доставка;`,
         `без данните за плащане Stripe не може да приеме депозит или плащане.`,
         `Ако не предоставиш тези данни, няма да можем да ти предоставим съответната услуга. Останалите данни (напр. предпочитания и незадължителни полета) са изцяло доброволни и отказът им не засяга достъпа ти до основната услуга.`]],
      ["5. Защо и на какво правно основание обработваме данните",
        [`Изпълнение на договор или преддоговорни действия (чл. 6, § 1, б. „б“ GDPR): регистрация и поддръжка на профила, обработка на запитване, поръчка, депозит, внос, проследяване и доставка.`,
         `Законово задължение (чл. 6, § 1, б. „в“): счетоводна и данъчна отчетност, митнически документи, задължения по Закона за мерките срещу изпирането на пари, когато са приложими.`,
         `Легитимен интерес (чл. 6, § 1, б. „е“): сигурност на сайта и предотвратяване на измами, поддържане на записи за защита при спор, техническа поддръжка и отстраняване на грешки. Преценили сме, че тези цели не накърняват неоправдано правата ти; можеш да поискаш обобщение на тази преценка на ${COMPANY.email} и да възразиш по всяко време (виж раздел 10).`,
         `Съгласие (чл. 6, § 1, б. „а“): бисквитки и подобни технологии, които не са строго необходими, персонализирани предложения, известия по имейл и push за спад в цената или нова кола по запазено търсене. Съгласието се оттегля по всяко време — от „Настройки за бисквитки“ във футъра или от профила — без това да засяга законосъобразността на обработването преди оттеглянето.`]],
      ["6. Бисквитки и подобни технологии",
        [`Не записваме и не четем нищо на твоето устройство извън строго необходимото, преди да си дал изрично съгласие за съответната категория. Отказът е толкова лесен, колкото приемането, и превключвателите са изключени по подразбиране.`,
         `Пълният списък с имена, цели и срокове е в Политиката за бисквитките. Ако някога включим статистика от трета страна (Google Analytics 4), тя ще се зарежда само след съгласие за категория „Статистика“, с отказано по подразбиране съгласие (Consent Mode) и без рекламни сигнали.`]],
      ["7. С кого споделяме данните",
        [`Споделяме данни само доколкото е необходимо и със следните категории получатели:`,
         `Хостинг и инфраструктура: Hetzner Online GmbH, сървъри в Германия (обработващ лични данни).`,
         `Имейли: Resend (транзакционни съобщения — потвърждения, известия, отговори на запитвания).`,
         `Плащания: Stripe Payments Europe — самостоятелен администратор за данните на картата ти; ние получаваме само резултата от плащането.`,
         `Превод на текстовете от обявите: Anthropic и Google. Изпращат се само данни от обявата (марка, модел, описание от търговеца), никога твои лични данни.`,
         `Вход с Google: Google Ireland Ltd, само ако сам избереш този начин на вход. Получаваме имейл, име и профилна снимка.`,
         `Проследяване на пратки: превозвачът (напр. Maersk) и услугата за проследяване на контейнери, с която работим.`,
         `Логистика и внос: спедитори, превозвачи, митнически агенти, пристанищни оператори и корейските ни партньори, доколкото е нужно за твоята поръчка.`,
         `Професионални консултанти: счетоводител, а при нужда адвокат или одитор, обвързани с поверителност.`,
         `Държавни органи, когато законът го изисква.`,
         `С всеки доставчик, който обработва лични данни от наше име, сме сключили договор по чл. 28 GDPR, който го задължава да обработва данните само по наши инструкции, да гарантира поверителност и подходящи технически и организационни мерки и да заличи или върне данните при прекратяване на услугата. Самостоятелните администратори (напр. Stripe, Google) обработват данните ти по собствените си политики за поверителност.`,
         `Не продаваме лични данни и не ги предоставяме на рекламни мрежи.`]],
      ["8. Предаване извън ЕС/ЕИП",
        [`Част от доставчиците ни (Anthropic, Google, Stripe) и партньорите ни в Южна Корея се намират извън ЕИП. Предаването се извършва въз основа на решение на Европейската комисия за адекватно ниво на защита, когато за съответния получател има такова (включително рамката EU–US Data Privacy Framework), а в останалите случаи — въз основа на стандартни договорни клаузи по чл. 46, § 2, б. „в“ GDPR, придружени при нужда от допълнителни мерки.`,
         `Към корейските партньори и превозвачите изпращаме само минимума, нужен за конкретната покупка и превоз. Данните за превод не съдържат лична информация. Копие от приложимите гаранции можеш да поискаш на ${COMPANY.email}.`]],
      ["9. Колко дълго пазим данните",
        [`Счетоводни регистри и финансови отчети: 10 години, считано от 1 януари на годината, следваща годината на съставянето им. Останалите счетоводни и данъчни документи се пазят за сроковете по Закона за счетоводството и ДОПК според вида им.`,
         `Профил и адрес: докато поддържаш профила. При изтриване премахваме профила, адреса, сесиите, passkeys и двуфакторните тайни; остават само документите, които сме длъжни да пазим по закон.`,
         `Запитвания без сключена сделка: до 2 години от последната кореспонденция.`,
         `Сесии: до 30 дни от последната активност. Технически записи и логове: до 90 дни.`,
         `Запис за съгласие: 12 месеца (след което питаме отново) и до 3 години като доказателство, че съгласието е било дадено или отказано.`,
         `Бисквитка с предпочитания: 90 дни от последната активност; изтриването на бисквитките я премахва веднага.`]],
      ["10. Твоите права",
        [`Спрямо личните си данни имаш право на: достъп и копие от данните (чл. 15); коригиране (чл. 16); изтриване (чл. 17); ограничаване на обработването (чл. 18); преносимост в машинно четим формат (чл. 20); възражение срещу обработване на основание легитимен интерес (чл. 21, § 1); оттегляне на съгласие по всяко време — от „Настройки за бисквитки“ във футъра, съответните превключватели в профила или имейл до нас.`,
         `Ако някога изпращаме съобщения с цел директен маркетинг, имаш безусловно право да възразиш по всяко време и без да посочваш причина; след възражение спираме тези съобщения (чл. 21, § 2–3).`,
         `Заявките са безплатни; изпрати ги на ${COMPANY.email}. Може да поискаме допълнителна информация, за да се уверим, че заявката е от теб. Отговаряме в сроковете по раздел 1.`,
         `Имаш право на жалба до Комисията за защита на личните данни, гр. София 1592, бул. „Проф. Цветан Лазаров“ № 2, kzld.bg. Ако си в Румъния — до ANSPDCP (dataprotection.ro), или до надзорния орган по местоживеенето ти.`]],
      ["11. Автоматизирано вземане на решения и профилиране",
        [`Класирането „Подходящи“ и предложенията за автомобили се основават на общи критерии за търсене и на предпочитанията, които сам си посочил или разгледал. Те са само помощно средство при търсенето, не пораждат правни последици за теб и не те засягат по подобен съществен начин, поради което не представляват автоматизирано вземане на решения или профилиране по смисъла на чл. 22 GDPR. Не влияят на цената, която виждаш, нито на условията, които получаваш.`]],
      ["12. Деца",
        [`Услугата е предназначена за лица над 18 години. Не събираме съзнателно данни на деца. Ако разберем, че сме получили такива, ги изтриваме.`]],
      ["13. Сигурност",
        [`Целият трафик е криптиран (HTTPS). Паролите се съхраняват само като Argon2id хеш. Сесиите са сървърни, с HttpOnly бисквитка, и могат да се прекратят от профила ти по всяко време; предлагаме двуфакторна защита и passkeys. Достъпът до данните е ограничен до лицата, които го изискват за работата си. Правим редовни резервни копия и водим одитен дневник на административните действия.`,
         `При нарушение на сигурността, което води до висок риск за правата ти, ще те уведомим и ще уведомим КЗЛД в сроковете по чл. 33–34 GDPR.`]],
      ["14. Промени в политиката",
        [`Всяка съществена промяна се отразява в номера на версията и датата на актуализация и — когато засяга съгласието ти — в нова версия, при която банерът за съгласие ще те попита отново.`]],
      ["Бележка",
        [`Този текст е изготвен добросъвестно и подробно, но не замества юридическа консултация. Преди да разчиташ на него търговски, дай го за преглед на адвокат.`]],
    ],
    PRIVACY_STAMP.bg
  ),
  cookies: doc(
    "Политика за бисквитките",
    `Нищо, което не е строго необходимо, не се записва и не се чете от твоето устройство, преди да си дал изрично съгласие. По-долу е всяко средство, което използваме, за какво служи, кой го поставя и колко живее.`,
    [
      ["1. Какво урежда тази политика и на какво основание",
        [`Политиката се отнася до всички технологии, чрез които съхраняваме информация на твоето устройство или получаваме достъп до вече съхранена информация — бисквитки, localStorage и sessionStorage, кеш на приложението и подобни идентификатори. Правилата важат еднакво за всички тях, независимо от техническото им наименование.`,
         `Съхраняването и достъпът се извършват съгласно чл. 5, § 3 от Директива 2002/58/ЕО (ePrivacy), транспонирана в българското законодателство със Закона за електронните съобщения. Когато чрез тези средства се обработват лични данни, обработването се извършва на основание съгласие (чл. 6, § 1, б. „а“ GDPR) за незадължителните категории и легитимен интерес или изпълнение на договор (чл. 6, § 1, б. „е“ и „б“ GDPR) за строго необходимите. Пълната информация за обработването на лични данни е в Политиката за поверителност.`,
         `Администратор: ${COMPANY.name}, ЕИК ${COMPANY.eik}, ${COMPANY.address}; ${COMPANY.email}; тел. ${COMPANY.phone}.`]],
      ["2. Как работи съгласието",
        [`При първото посещение показваме банер с три равнопоставени избора: „Отказвам всички“, „Настройки“ и „Приемам всички“. Трите бутона са с еднакъв визуален приоритет — еднакъв размер, контраст и разположение.`,
         `Превключвателите за незадължителните категории са изключени по подразбиране. Съгласието е отделно за всяка категория — можеш да приемеш едната и да откажеш другата.`,
         `Отказът е толкова лесен, колкото приемането, и се постига с еднакъв брой действия. Не използваме подвеждащи оформления, предварително отметнати полета или „стена за бисквитки“ — отказът не ограничава достъпа ти до сайта и услугите.`,
         `Продължаването на сърфирането, скролването или затварянето на банера не се третира като съгласие. Докато не направиш избор, не се зареждат незадължителни средства.`,
         `Изборът се записва — категории, дата и версия на политиката — и се пази 12 месеца, след което питаме отново, както и при съществена промяна на тази политика. Записът, който доказва даването или отказа на съгласие, се съхранява до 3 години като доказателство по чл. 7, § 1 GDPR.`,
         `Можеш да промениш или оттеглиш избора си по всяко време от „Настройки за бисквитки“ във футъра на всяка страница. При отказ или оттегляне съответните средства се изтриват веднага; оттеглянето не засяга законосъобразността на обработването преди него.`]],
      ["3. Строго необходими (без съгласие)",
        [`encar_session — държи те влязъл в профила. HttpOnly и недостъпна за скриптове, Secure (само по HTTPS) и SameSite=Lax, което пази заявките ти от подправяне от друг сайт (CSRF) — отделен маркер за това не използваме. Изтрива се при изход от профила. Бисквитка, наша · до 30 дни от последната активност.`,
         `ab_consent — записва самия ти избор за бисквитките. Необходима е, защото пази и отказа ти — без нея банерът би те питал отново при всяко зареждане. Бисквитка, наша · 12 месеца.`,
         `encar.lang / encar.currency / encar.theme — избраният от теб език, валута и тема (светла/тъмна). localStorage, наш · до изтриване от теб.`,
         `encar.favourites / encar.searches — за посетители без профил: колите и търсенията, които сам си запазил на устройството си. localStorage, наш · до изтриване от теб.`,
         `Технически кеш (encar.cms.* и кеш на приложението) — кеш на текстовете и страниците, за да не се презареждат при всяко отваряне. Не съдържа лични данни и не идентифицира устройството. Кеш, наш · до изчистване на кеша.`,
         `Тези средства са строго необходими, за да работи сайтът и услугата, която сам поиска, затова законът не изисква съгласие за тях. Те не могат да бъдат изключени от настройките, но можеш да ги блокираш от браузъра си (виж раздел 9).`]],
      ["4. Персонализация (със съгласие)",
        [`ab_taste — кои марки, модели и горива разглеждаш, за да подредим подходящите автомобили. Бисквитка, наша · 90 дни.`,
         `ab_vid — случаен идентификатор на браузъра, свързан със същия профил на предпочитания. Не съдържа име или имейл. Бисквитка, наша · 90 дни.`,
         `ab_track — номерата, които вече си проверявал в „Проследи автомобила“, за да не ги въвеждаш отново. Бисквитка, наша · 90 дни.`,
         `Тези данни служат единствено за подреждане на резултатите от търсенето. Не пораждат правни последици за теб, не влияят на цената, която виждаш, нито на условията, които получаваш, и не представляват профилиране по смисъла на чл. 22 GDPR.`]],
      ["5. Статистика (със съгласие)",
        [`Брояч на отваряния на обява — изпраща се към нашия сървър, за да знаем кои автомобили се търсят. Не записва бисквитка на устройството ти и не се свързва с профила ти. Сървърно събитие, наше · агрегирано, без идентификатор.`,
         `Броячът работи изцяло на наш сървър и не съхранява и не чете информация от устройството ти, но го поставяме под съгласие, за да ти дадем пълен контрол. Използваме резултатите само в обобщен вид.`,
         `Ако в бъдеще включим Google Analytics 4, той ще се зарежда само след съгласие за тази категория, с отказани по подразбиране разрешения (Google Consent Mode v2), с анонимизиран IP и без рекламни сигнали. Към датата на тази версия не е активен и никакъв скрипт на Google не се зарежда за целите на статистиката.`]],
      ["6. Средства на трети страни при плащане и вход",
        [`Когато сам започнеш плащане или избереш вход с Google, съответният доставчик може да постави собствени бисквитки на устройството ти. Те са необходими за услугата, която си поискал, и за предотвратяване на измами:`,
         `Stripe Payments Europe — бисквитки за обработка на плащането и откриване на измами. Зареждат се само на страниците за плащане и депозит. Stripe действа като самостоятелен администратор; условията му са на stripe.com/privacy.`,
         `Google Ireland Ltd — бисквитки за удостоверяване, само ако избереш вход с Google. Условията са на policies.google.com/privacy.`,
         `Ако не използваш тези функции, никакви средства на трети страни не се зареждат. Нямаме контрол върху сроковете на бисквитките, поставени от тези доставчици — актуалните срокове са в техните политики.`]],
      ["7. Маркетинг и реклама",
        [`Не използваме. Няма рекламни мрежи, няма ретаргетинг, няма пиксели или скриптове на трети страни за рекламни цели, няма продажба или обмен на данни с рекламодатели. Затова в настройките няма категория „Маркетинг“ — няма какво да включиш или изключиш.`]],
      ["8. Какво става, ако откажеш",
        [`Сайтът работи напълно: разглеждане, търсене, регистрация, поръчка, плащане и проследяване остават достъпни.`,
         `Няма да подреждаме предложенията по твоите интереси и ще виждаш общото класиране.`,
         `Ще въвеждаш отново номерата в „Проследи автомобила“.`,
         `Няма да отчитаме твоите отваряния на обяви в статистиката.`]],
      ["9. Управление и изтриване от браузъра",
        [`Освен от „Настройки за бисквитки“ можеш да изтриеш или блокираш средствата и от браузъра си. Локалното хранилище (localStorage) се изчиства чрез изтриване на данните за сайта, а не само на бисквитките.`,
         `Chrome: Настройки → Поверителност и сигурност → Бисквитки и други данни за сайтове.`,
         `Safari: Настройки → Поверителност → Управление на данните за уебсайтове.`,
         `Firefox: Настройки → Поверителност и защита → Бисквитки и данни за сайтове.`,
         `Edge: Настройки → Бисквитки и разрешения за сайтове.`,
         `Блокирането на строго необходимите средства може да наруши входа в профила и запазването на избора ти за бисквитки. Сигналите за поверителност на ниво браузър (Do Not Track, Global Privacy Control) днес нямат правно действие в ЕС и не заместват избора ти в банера — водещ е изборът, който направиш в „Настройки за бисквитки“.`]],
      ["10. Твоите права и връзка с личните данни",
        [`Когато чрез описаните средства се обработват лични данни, имаш всички права по GDPR — достъп, коригиране, изтриване, ограничаване, преносимост, възражение и оттегляне на съгласие. Начинът на упражняване и сроковете за отговор са в Политиката за поверителност.`,
         `Имаш право на жалба до Комисията за защита на личните данни, гр. София 1592, бул. „Проф. Цветан Лазаров“ № 2, kzld.bg, или до надзорния орган по местоживеенето ти.`]],
      ["11. Деца",
        [`Услугата е предназначена за лица над 18 години. Не поставяме съзнателно средства за персонализация или статистика на устройства на деца.`]],
      ["12. Промени в политиката",
        [`Всяка съществена промяна се отразява в номера на версията и датата на актуализация. Когато промяната засяга категориите, за които си дал съгласие, банерът ще те попита отново, а предишният ти избор няма да се пренася автоматично.`]],
      ["13. Въпроси",
        [`Пиши на ${COMPANY.email}. Как обработваме личните данни е описано в Политиката за поверителност.`]],
      ["Бележка",
        [`Този текст е изготвен добросъвестно и подробно, но не замества юридическа консултация. Преди да разчиташ на него търговски, дай го за преглед на адвокат.`]],
    ],
    PRIVACY_STAMP.bg
  ),
};

const RO = {

  terms: doc(
    "Termeni și condiții",
    `Acești termeni reglementează folosirea site-ului ${COMPANY.site} și comanda unei mașini prin ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
    [
      ["Ce facem",
        [`Afișăm mașini scoase la vânzare în Coreea de Sud, traduse în bulgară, română și engleză.`,
         `Prețul afișat este prețul final estimat până la adresa ta: mașina, transportul maritim, taxele vamale și TVA, dacă pagina anunțului nu spune altfel.`]],
      ["Anunțurile nu ne aparțin",
        [`Datele și fotografiile provin din piața coreeană și se actualizează periodic. O mașină poate fi vândută înainte să primim date noi.`,
         `De aceea un anunț este o invitație la cerere, nu o ofertă obligatorie. Prețul obligatoriu îl primești în confirmarea noastră scrisă.`]],
      ["Comandă și plată",
        [`După cerere confirmăm disponibilitatea, prețul final și termenul, apoi emitem documentul de plată. Contractul se încheie când confirmăm comanda în scris.`,
         `Plata se face prin transfer bancar către ${COMPANY.name}. Nu acceptăm numerar pentru mașini.`]],
      ["Termene și livrare",
        [`Termenul orientativ de la comanda confirmată până la livrare este de 6-10 săptămâni și depinde de orarele navelor și de procedurile portuare și vamale.`,
         `Datele din „Urmărește mașina” sunt estimări. Ultimul pas — livrarea la adresa ta — se calculează la aproximativ șapte zile după sosirea în portul european.`]],
      ["Starea mașinii",
        [`Mașinile sunt second-hand. Afișăm raportul de inspecție și istoricul, în măsura în care sursa le pune la dispoziție.`,
         `O mașină folosită poate avea uzură care nu apare în documente. Dacă ai dubii, cere o verificare suplimentară înainte de comandă.`]],
      ["Dreptul de retragere",
        [`Dacă ești consumator, îți păstrezi drepturile legale, inclusiv dreptul de retragere atunci când se aplică tranzacției tale.`,
         `O mașină adusă la cererea ta individuală expresă poate intra în excepțiile de la dreptul de retragere. Îți spunem ce se aplică înainte de plată.`]],
      ["Răspundere",
        [`Nu răspundem pentru întârzieri provocate de transportatori, porturi, vamă sau autorități, dar te informăm imediat ce le aflăm.`,
         `Nu răspundem pentru prejudicii indirecte, precum profit nerealizat sau costul închirierii altei mașini.`]],
      ["Litigii",
        [`Se aplică legea bulgară. Litigiile se soluționează de instanța bulgară competentă, dacă o normă imperativă de protecție a consumatorului nu prevede altfel.`,
         `Poți folosi și platforma europeană de soluționare online a litigiilor.`]],
      ["Contact",
        [`Scrie-ne la ${COMPANY.email}. Răspundem în două zile lucrătoare.`]],
    ]
  ),
  privacy: doc(
    "Politica de confidențialitate",
    `${COMPANY.name}, cod unic ${COMPANY.eik}, cu sediul social și adresa de administrare în ${COMPANY.address}, este operatorul datelor personale prelucrate prin ${COMPANY.site}. Această politică explică ce date colectăm, în baza cărui temei, de unde le primim, cu cine le împărtășim, cât timp le păstrăm și cum îți exerciți drepturile conform Regulamentului (UE) 2016/679 (GDPR) și legislației bulgare privind protecția datelor.`,
    [
      ["1. Cine răspunde pentru datele tale",
        [`Operator: ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
         `Adresă: ${COMPANY.address}.`,
         `Contact pentru întrebări și cereri GDPR: ${COMPANY.email}; tel. ${COMPANY.phone}.`,
         `Nu avem obligația de a numi un responsabil cu protecția datelor și nu am numit unul. Cererile sunt tratate de administrator și primești răspuns în termen de o lună de la primirea lor. În cazul cererilor complexe sau numeroase, termenul poate fi prelungit cu încă două luni, iar te vom informa despre prelungire și motivele ei în prima lună.`]],
      ["2. Ce date prelucrăm",
        [`Cont: e-mail, nume (dacă îl completezi), parola — păstrată doar ca hash ireversibil (Argon2id) — și datele pentru autentificarea în doi pași sau passkey, dacă le-ai activat.`,
         `Livrare și facturare: nume, stradă, oraș, cod poștal, țară și telefon — numai dacă le introduci.`,
         `Cereri și corespondență: mesajul, e-mailul și telefonul pe care ni le trimiți, plus răspunsurile noastre.`,
         `Plăți și depozite: sumă, stare, dată și identificatorul plății. Datele cardului se introduc direct la Stripe — noi nu vedem și nu stocăm niciodată numărul cardului.`,
         `Transporturi: numerele de conosament și de container legate de comanda ta, evenimentele de la transportator și țara pentru ultimul pas al livrării.`,
         `Date tehnice: adresa IP, tipul de browser și dispozitiv, momentul cererii și înregistrările de autentificare (inclusiv lista sesiunilor active, pe care o vezi în cont).`,
         `Înregistrarea consimțământului tău: ce categorii de cookie-uri ai acceptat sau refuzat, când și față de ce versiune a politicii.`,
         `Preferințe (numai cu consimțământ): ce mărci, modele și combustibili deschizi, într-un cookie de pe dispozitivul tău, valabil 90 de zile.`]],
      ["3. De unde primim datele",
        [`Cele mai multe date le primim direct de la tine. În unele cazuri primim date legate de tine și de la terți:`,
         `de la transportator și de la serviciul de urmărire a containerelor — evenimentele transportului, starea containerului și a conosamentului;`,
         `de la Google — e-mail, nume și poza de profil, doar dacă alegi autentificarea cu Google;`,
         `de la Stripe — rezultatul, starea și identificatorul plății tale (dar nu datele cardului);`,
         `de la partenerii noștri logistici, vamali și coreeni — datele necesare pentru comanda și transportul tău.`,
         `Categoriile acestor date și temeiurile juridice ale prelucrării lor sunt aceleași cu cele descrise în această politică.`]],
      ["4. Caracterul obligatoriu al furnizării datelor",
        [`Furnizarea unei părți din date este necesară pentru a încheia și executa contractul cu tine sau pentru a respecta legea:`,
         `fără e-mail și parolă nu putem crea și menține un cont;`,
         `fără nume, adresă și telefon nu putem procesa comanda, importul și livrarea;`,
         `fără datele de plată, Stripe nu poate accepta un depozit sau o plată.`,
         `Dacă nu furnizezi aceste date, nu îți vom putea oferi serviciul respectiv. Restul datelor (de ex. preferințele și câmpurile opționale) sunt complet voluntare, iar refuzul lor nu afectează accesul tău la serviciul principal.`]],
      ["5. De ce și în baza cărui temei prelucrăm datele",
        [`Executarea contractului sau demersuri precontractuale (art. 6 alin. 1 lit. b GDPR): înregistrarea și administrarea contului, tratarea cererii, comanda, depozitul, importul, urmărirea și livrarea.`,
         `Obligație legală (art. 6 alin. 1 lit. c): contabilitate și fiscalitate, documente vamale, obligații privind prevenirea spălării banilor, când sunt aplicabile.`,
         `Interes legitim (art. 6 alin. 1 lit. f): securitatea site-ului și prevenirea fraudei, păstrarea dovezilor în caz de litigiu, mentenanță tehnică și remedierea erorilor. Am evaluat că aceste scopuri nu îți afectează în mod nejustificat drepturile; poți cere un rezumat al acestei evaluări la ${COMPANY.email} și te poți opune oricând (vezi secțiunea 10).`,
         `Consimțământ (art. 6 alin. 1 lit. a): cookie-uri și tehnologii similare care nu sunt strict necesare, recomandări personalizate, notificări prin e-mail și push pentru scăderi de preț sau o mașină nouă într-o căutare salvată. Consimțământul se retrage oricând — din „Setări cookie-uri” din footer sau din cont — fără a afecta legalitatea prelucrării de dinaintea retragerii.`]],
      ["6. Cookie-uri și tehnologii similare",
        [`Nu scriem și nu citim nimic pe dispozitivul tău în afara strictului necesar înainte să îți dai consimțământul explicit pentru categoria respectivă. Refuzul este la fel de simplu ca acceptarea, iar comutatoarele sunt dezactivate implicit.`,
         `Lista completă cu nume, scopuri și durate este în Politica de cookie-uri. Dacă vom activa vreodată statistici de la un terț (Google Analytics 4), acestea se vor încărca doar după consimțământ pentru categoria „Statistici”, cu permisiuni refuzate implicit (Consent Mode) și fără semnale publicitare.`]],
      ["7. Cu cine împărtășim datele",
        [`Împărtășim datele doar în măsura necesară și cu următoarele categorii de destinatari:`,
         `Găzduire și infrastructură: Hetzner Online GmbH, servere în Germania (persoană împuternicită).`,
         `E-mailuri: Resend (mesaje tranzacționale — confirmări, notificări, răspunsuri la cereri).`,
         `Plăți: Stripe Payments Europe — operator independent pentru datele cardului; noi primim doar rezultatul plății.`,
         `Traducerea textelor din anunțuri: Anthropic și Google. Se trimit doar date din anunț (marcă, model, descrierea dealerului), niciodată datele tale personale.`,
         `Autentificare cu Google: Google Ireland Ltd, doar dacă alegi tu această metodă. Primim e-mailul, numele și poza de profil.`,
         `Urmărirea transporturilor: transportatorul (de ex. Maersk) și serviciul de urmărire a containerelor cu care lucrăm.`,
         `Logistică și import: case de expediții, transportatori, agenți vamali, operatori portuari și partenerii noștri coreeni, cât este necesar pentru comanda ta.`,
         `Consultanți profesioniști: contabil și, la nevoie, avocat sau auditor, obligați la confidențialitate.`,
         `Autorități, când legea o cere.`,
         `Cu fiecare furnizor care prelucrează date personale în numele nostru am încheiat un contract conform art. 28 GDPR, care îl obligă să prelucreze datele numai după instrucțiunile noastre, să asigure confidențialitatea și măsuri tehnice și organizatorice adecvate și să șteargă sau să returneze datele la încetarea serviciului. Operatorii independenți (de ex. Stripe, Google) prelucrează datele tale conform propriilor politici de confidențialitate.`,
         `Nu vindem date personale și nu le oferim rețelelor de publicitate.`]],
      ["8. Transferuri în afara UE/SEE",
        [`Unii furnizori (Anthropic, Google, Stripe) și partenerii noștri din Coreea de Sud se află în afara SEE. Transferul are loc în baza unei decizii de adecvare a Comisiei Europene, când există una pentru destinatarul respectiv (inclusiv EU–US Data Privacy Framework), iar în celelalte cazuri în baza clauzelor contractuale standard conform art. 46 alin. 2 lit. c GDPR, însoțite la nevoie de măsuri suplimentare.`,
         `Către partenerii coreeni și transportatori trimitem doar minimul necesar pentru achiziția și transportul respectiv. Datele trimise pentru traducere nu conțin informații personale. O copie a garanțiilor aplicabile poate fi cerută la ${COMPANY.email}.`]],
      ["9. Cât timp păstrăm datele",
        [`Registre contabile și situații financiare: 10 ani, începând cu 1 ianuarie a anului următor celui în care au fost întocmite. Celelalte documente contabile și fiscale se păstrează pe termenele prevăzute de legislația bulgară, în funcție de tipul lor.`,
         `Cont și adresă: cât timp păstrezi contul. La ștergere eliminăm contul, adresa, sesiunile, passkeys și secretele de autentificare în doi pași; rămân doar documentele pe care legea ne obligă să le păstrăm.`,
         `Cereri fără tranzacție încheiată: până la 2 ani de la ultima corespondență.`,
         `Sesiuni: până la 30 de zile de la ultima activitate. Jurnale tehnice: până la 90 de zile.`,
         `Înregistrarea consimțământului: 12 luni (după care întrebăm din nou) și până la 3 ani ca dovadă că a fost dat sau refuzat.`,
         `Cookie-ul de preferințe: 90 de zile de la ultima activitate; ștergerea cookie-urilor îl elimină imediat.`]],
      ["10. Drepturile tale",
        [`În legătură cu datele tale personale ai dreptul la: acces și o copie a datelor (art. 15); rectificare (art. 16); ștergere (art. 17); restricționarea prelucrării (art. 18); portabilitate în format prelucrabil automat (art. 20); opoziție față de prelucrarea bazată pe interes legitim (art. 21 alin. 1); retragerea consimțământului oricând — din „Setări cookie-uri” din footer, comutatoarele din cont sau un e-mail către noi.`,
         `Dacă vom trimite vreodată mesaje de marketing direct, ai dreptul necondiționat de a te opune oricând și fără să indici un motiv; după opoziție oprim aceste mesaje (art. 21 alin. 2–3).`,
         `Cererile sunt gratuite; trimite-le la ${COMPANY.email}. Putem cere informații suplimentare pentru a ne asigura că cererea vine de la tine. Răspundem în termenele din secțiunea 1.`,
         `Ai dreptul de a depune plângere la ANSPDCP (B-dul G-ral. Gheorghe Magheru 28-30, București, dataprotection.ro), la Comisia bulgară pentru protecția datelor personale (Sofia 1592, bd. „Prof. Tsvetan Lazarov” nr. 2, kzld.bg) sau la autoritatea de supraveghere din țara ta de reședință.`]],
      ["11. Decizii automatizate și profilare",
        [`Clasamentul „Potrivite” și recomandările de mașini se bazează pe criterii generale de căutare și pe preferințele pe care le-ai indicat sau consultat tu. Sunt doar un ajutor la căutare, nu produc efecte juridice asupra ta și nu te afectează în mod similar semnificativ, deci nu constituie decizii automatizate sau profilare în sensul art. 22 GDPR. Nu influențează prețul afișat, nici condițiile pe care le primești.`]],
      ["12. Copii",
        [`Serviciul este destinat persoanelor peste 18 ani. Nu colectăm cu bună știință date ale copiilor. Dacă aflăm că am primit astfel de date, le ștergem.`]],
      ["13. Securitate",
        [`Tot traficul este criptat (HTTPS). Parolele sunt păstrate doar ca hash Argon2id. Sesiunile sunt pe server, cu cookie HttpOnly, și pot fi închise oricând din contul tău; oferim autentificare în doi pași și passkeys. Accesul la date este limitat la persoanele care au nevoie de el pentru munca lor. Facem copii de siguranță periodice și păstrăm un jurnal de audit al acțiunilor administrative.`,
         `În caz de încălcare a securității care duce la un risc ridicat pentru drepturile tale, te vom informa pe tine și autoritatea de supraveghere în termenele din art. 33–34 GDPR.`]],
      ["14. Modificări ale politicii",
        [`Orice modificare importantă se reflectă în numărul versiunii și în data actualizării și — când îți afectează consimțământul — într-o versiune nouă, caz în care bannerul de consimțământ te va întreba din nou.`]],
      ["Notă",
        [`Textul este redactat cu bună-credință și în detaliu, dar nu înlocuiește consultanța juridică. Cere avizul unui avocat înainte să te bazezi comercial pe el.`]],
    ],
    PRIVACY_STAMP.ro
  ),
  cookies: doc(
    "Politica de cookie-uri",
    `Nimic care nu este strict necesar nu se scrie și nu se citește de pe dispozitivul tău înainte să îți dai consimțământul explicit. Mai jos este fiecare mijloc pe care îl folosim, la ce servește, cine îl plasează și cât trăiește.`,
    [
      ["1. Ce reglementează această politică și în baza cărui temei",
        [`Politica se referă la toate tehnologiile prin care stocăm informații pe dispozitivul tău sau accesăm informații deja stocate — cookie-uri, localStorage și sessionStorage, cache-ul aplicației și identificatori similari. Regulile se aplică la fel pentru toate, indiferent de denumirea lor tehnică.`,
         `Stocarea și accesul se realizează conform art. 5 alin. 3 din Directiva 2002/58/CE (ePrivacy), transpusă în legislația bulgară prin Legea privind comunicațiile electronice. Când prin aceste mijloace se prelucrează date personale, prelucrarea are loc în baza consimțământului (art. 6 alin. 1 lit. a GDPR) pentru categoriile opționale și în baza interesului legitim sau a executării contractului (art. 6 alin. 1 lit. f și b GDPR) pentru cele strict necesare. Informația completă despre prelucrarea datelor personale este în Politica de confidențialitate.`,
         `Operator: ${COMPANY.name}, cod unic ${COMPANY.eik}, ${COMPANY.address}; ${COMPANY.email}; tel. ${COMPANY.phone}.`]],
      ["2. Cum funcționează consimțământul",
        [`La prima vizită afișăm un banner cu trei opțiuni egale: „Refuz toate”, „Setări” și „Accept toate”. Cele trei butoane au aceeași prioritate vizuală — aceeași dimensiune, contrast și poziționare.`,
         `Comutatoarele categoriilor opționale sunt dezactivate implicit. Consimțământul este separat pentru fiecare categorie — poți accepta una și refuza cealaltă.`,
         `Refuzul este la fel de simplu ca acceptarea și se obține cu același număr de acțiuni. Nu folosim design înșelător, casete bifate în avans sau un „cookie wall” — refuzul nu îți limitează accesul la site și la servicii.`,
         `Continuarea navigării, derularea paginii sau închiderea bannerului nu se consideră consimțământ. Până când nu faci o alegere, nu se încarcă mijloace opționale.`,
         `Alegerea se salvează — categorii, dată și versiunea politicii — și se păstrează 12 luni, după care întrebăm din nou, la fel ca la o modificare importantă a acestei politici. Înregistrarea care dovedește acordarea sau refuzul consimțământului se păstrează până la 3 ani, ca dovadă conform art. 7 alin. 1 GDPR.`,
         `Poți schimba sau retrage alegerea oricând din „Setări cookie-uri”, în footerul fiecărei pagini. La refuz sau retragere, mijloacele respective se șterg imediat; retragerea nu afectează legalitatea prelucrării anterioare.`]],
      ["3. Strict necesare (fără consimțământ)",
        [`encar_session — te menține autentificat. HttpOnly și inaccesibil scripturilor, Secure (numai prin HTTPS) și SameSite=Lax, ceea ce îți protejează cererile de falsificare de pe alt site (CSRF) — nu folosim un token separat pentru asta. Se șterge la deconectare. Cookie, al nostru · până la 30 de zile de la ultima activitate.`,
         `ab_consent — înregistrează chiar alegerea ta privind cookie-urile. Este necesar pentru că păstrează și refuzul tău — fără el bannerul te-ar întreba la fiecare încărcare. Cookie, al nostru · 12 luni.`,
         `encar.lang / encar.currency / encar.theme — limba, moneda și tema (deschis/închis) alese de tine. localStorage, al nostru · până la ștergerea de către tine.`,
         `encar.favourites / encar.searches — pentru vizitatorii fără cont: mașinile și căutările salvate de tine pe dispozitivul tău. localStorage, al nostru · până la ștergerea de către tine.`,
         `Cache tehnic (encar.cms.* și cache-ul aplicației) — cache al textelor și paginilor, ca să nu se reîncarce la fiecare deschidere. Nu conține date personale și nu identifică dispozitivul. Cache, al nostru · până la golirea cache-ului.`,
         `Aceste mijloace sunt strict necesare pentru funcționarea site-ului și a serviciului cerut de tine, deci legea nu impune consimțământ pentru ele. Nu pot fi dezactivate din setări, dar le poți bloca din browserul tău (vezi secțiunea 9).`]],
      ["4. Personalizare (cu consimțământ)",
        [`ab_taste — ce mărci, modele și combustibili deschizi, ca să ordonăm mașinile potrivite. Cookie, al nostru · 90 de zile.`,
         `ab_vid — un identificator aleatoriu al browserului, legat de același profil de preferințe. Nu conține nume sau e-mail. Cookie, al nostru · 90 de zile.`,
         `ab_track — numerele verificate deja în „Urmărește mașina”, ca să nu le reintroduci. Cookie, al nostru · 90 de zile.`,
         `Aceste date servesc exclusiv la ordonarea rezultatelor căutării. Nu produc efecte juridice asupra ta, nu influențează prețul afișat, nici condițiile pe care le primești, și nu constituie profilare în sensul art. 22 GDPR.`]],
      ["5. Statistici (cu consimțământ)",
        [`Contorul de deschideri ale unui anunț — se trimite către serverul nostru, ca să știm ce mașini se caută. Nu scrie un cookie pe dispozitivul tău și nu se leagă de contul tău. Eveniment de server, al nostru · agregat, fără identificator.`,
         `Contorul funcționează integral pe serverul nostru și nu stochează și nu citește informații de pe dispozitivul tău, dar îl punem sub consimțământ ca să îți dăm control complet. Folosim rezultatele doar în formă agregată.`,
         `Dacă vom activa în viitor Google Analytics 4, se va încărca doar după consimțământ pentru această categorie, cu permisiuni refuzate implicit (Google Consent Mode v2), IP anonimizat și fără semnale publicitare. La data acestei versiuni nu este activ și niciun script Google nu se încarcă în scopuri statistice.`]],
      ["6. Mijloace ale terților la plată și autentificare",
        [`Când începi tu o plată sau alegi autentificarea cu Google, furnizorul respectiv poate plasa propriile cookie-uri pe dispozitivul tău. Ele sunt necesare pentru serviciul cerut de tine și pentru prevenirea fraudei:`,
         `Stripe Payments Europe — cookie-uri pentru procesarea plății și detectarea fraudei. Se încarcă doar pe paginile de plată și de depozit. Stripe acționează ca operator independent; condițiile sale sunt pe stripe.com/privacy.`,
         `Google Ireland Ltd — cookie-uri de autentificare, doar dacă alegi autentificarea cu Google. Condițiile sunt pe policies.google.com/privacy.`,
         `Dacă nu folosești aceste funcții, nu se încarcă niciun mijloc al terților. Nu avem control asupra duratelor cookie-urilor plasate de acești furnizori — duratele actuale sunt în politicile lor.`]],
      ["7. Marketing și publicitate",
        [`Nu folosim. Fără rețele de publicitate, fără retargeting, fără pixeli sau scripturi ale terților în scopuri publicitare, fără vânzarea sau schimbul de date cu advertiseri. De aceea în setări nu există o categorie „Marketing” — nu ai ce să activezi sau să dezactivezi.`]],
      ["8. Ce se întâmplă dacă refuzi",
        [`Site-ul funcționează complet: navigarea, căutarea, înregistrarea, comanda, plata și urmărirea rămân disponibile.`,
         `Nu vom ordona recomandările după interesele tale și vei vedea clasamentul general.`,
         `Vei reintroduce numerele în „Urmărește mașina”.`,
         `Nu vom contoriza deschiderile tale de anunțuri în statistici.`]],
      ["9. Administrare și ștergere din browser",
        [`În afară de „Setări cookie-uri”, poți șterge sau bloca mijloacele și din browserul tău. Stocarea locală (localStorage) se golește prin ștergerea datelor site-ului, nu doar a cookie-urilor.`,
         `Chrome: Setări → Confidențialitate și securitate → Cookie-uri și alte date ale site-urilor.`,
         `Safari: Setări → Confidențialitate → Gestionează datele site-urilor web.`,
         `Firefox: Setări → Confidențialitate și securitate → Cookie-uri și date ale site-urilor.`,
         `Edge: Setări → Cookie-uri și permisiuni pentru site-uri.`,
         `Blocarea mijloacelor strict necesare poate împiedica autentificarea și salvarea alegerii tale privind cookie-urile. Semnalele de confidențialitate la nivel de browser (Do Not Track, Global Privacy Control) nu au astăzi efect juridic în UE și nu înlocuiesc alegerea din banner — determinantă este alegerea făcută în „Setări cookie-uri”.`]],
      ["10. Drepturile tale și legătura cu datele personale",
        [`Când prin mijloacele descrise se prelucrează date personale, ai toate drepturile prevăzute de GDPR — acces, rectificare, ștergere, restricționare, portabilitate, opoziție și retragerea consimțământului. Modul de exercitare și termenele de răspuns sunt în Politica de confidențialitate.`,
         `Ai dreptul de a depune plângere la ANSPDCP (B-dul G-ral. Gheorghe Magheru 28-30, București, dataprotection.ro), la Comisia bulgară pentru protecția datelor personale (Sofia 1592, bd. „Prof. Tsvetan Lazarov” nr. 2, kzld.bg) sau la autoritatea de supraveghere din țara ta de reședință.`]],
      ["11. Copii",
        [`Serviciul este destinat persoanelor peste 18 ani. Nu plasăm cu bună știință mijloace de personalizare sau de statistică pe dispozitivele copiilor.`]],
      ["12. Modificări ale politicii",
        [`Orice modificare importantă se reflectă în numărul versiunii și în data actualizării. Când modificarea afectează categoriile pentru care ți-ai dat consimțământul, bannerul te va întreba din nou, iar alegerea anterioară nu se va transfera automat.`]],
      ["13. Întrebări",
        [`Scrie la ${COMPANY.email}. Modul în care prelucrăm datele personale este descris în Politica de confidențialitate.`]],
      ["Notă",
        [`Textul este redactat cu bună-credință și în detaliu, dar nu înlocuiește consultanța juridică. Cere avizul unui avocat înainte să te bazezi comercial pe el.`]],
    ],
    PRIVACY_STAMP.ro
  ),
};

const EN = {

  terms: doc(
    "Terms of service",
    `These terms cover the use of ${COMPANY.site} and ordering a car through ${COMPANY.name}, company number ${COMPANY.eik}.`,
    [
      ["What we do",
        [`We show cars offered for sale in South Korea, translated into Bulgarian, Romanian and English.`,
         `The price you see is the estimated final price to your address: the car, sea freight, customs duty and VAT, unless the listing page says otherwise.`]],
      ["The listings are not ours",
        [`Data and photos come from the Korean market and are refreshed periodically. A car can be sold before we receive updated data.`,
         `A listing is therefore an invitation to enquire, not a binding offer. A binding price comes in our written confirmation.`]],
      ["Ordering and payment",
        [`After your enquiry we confirm availability, the final price and the lead time, then issue the payment document. The contract is formed when we confirm your order in writing.`,
         `Payment is by bank transfer to ${COMPANY.name}. We do not accept cash for vehicles.`]],
      ["Lead times and delivery",
        [`From a confirmed order to delivery usually takes 6 to 10 weeks, depending on sailing schedules and on port and customs procedures.`,
         `Dates on the "Track my vehicle" page are estimates. The final step — delivery to your address — is calculated as roughly seven days after arrival at the European port.`]],
      ["Condition of the car",
        [`The cars are used. We show the inspection report and the history as far as the source makes them available.`,
         `A used car can have wear that the paperwork does not record. If in doubt, ask for an extra inspection before you order.`]],
      ["Right of withdrawal",
        [`If you are a consumer, you keep your statutory rights, including the right of withdrawal where it applies to your transaction.`,
         `A car imported on your express individual instruction may fall within the exceptions to that right. We will tell you which applies before you pay.`]],
      ["Liability",
        [`We are not liable for delays caused by carriers, ports, customs or authorities outside our control, but we always pass them on as soon as we learn of them.`,
         `We are not liable for indirect losses such as lost profit or the cost of hiring another car.`]],
      ["Disputes",
        [`Bulgarian law applies. Disputes go to the competent Bulgarian court, unless a mandatory consumer rule says otherwise.`,
         `You may also use the European Commission's online dispute resolution platform.`]],
      ["Contact",
        [`Write to ${COMPANY.email}. We answer within two working days.`]],
    ]
  ),
  privacy: doc(
    "Privacy policy",
    `${COMPANY.name}, company number ${COMPANY.eik}, with its registered seat and management address at ${COMPANY.address}, is the controller of the personal data processed through ${COMPANY.site}. This policy explains what data we collect, on what basis, where we get it from, who we share it with, how long we keep it and how you exercise your rights under Regulation (EU) 2016/679 (GDPR) and Bulgarian data protection law.`,
    [
      ["1. Who is responsible for your data",
        [`Controller: ${COMPANY.name}, company number ${COMPANY.eik}.`,
         `Address: ${COMPANY.address}.`,
         `Contact for questions and GDPR requests: ${COMPANY.email}; phone ${COMPANY.phone}.`,
         `We are not required to appoint a data protection officer and have not appointed one. Requests are handled by the manager and answered within one month of receipt. For complex or numerous requests the deadline may be extended by a further two months, and we will tell you about the extension and the reasons for it within the first month.`]],
      ["2. What data we process",
        [`Account: email, name (if you fill it in), password — kept only as an irreversible hash (Argon2id) — and two-factor or passkey data if you have switched either on.`,
         `Delivery and invoicing: name, street, city, post code, country and phone — only if you enter them.`,
         `Enquiries and correspondence: the message, email and phone you send us, and our replies.`,
         `Payments and deposits: amount, status, date and the payment reference. Your card details are entered directly with Stripe — we never see or store a card number.`,
         `Shipments: the bill of lading and container numbers tied to your order, the carrier's events, and the country for the final delivery step.`,
         `Technical data: IP address, browser and device type, request time and sign-in records (including the list of active sessions you can see in your account).`,
         `Your consent record: which cookie categories you accepted or refused, when, and against which version of this policy.`,
         `Preferences (only with consent): which makes, models and fuels you browse, in a cookie on your own device for 90 days.`]],
      ["3. Where we get the data from",
        [`Most data comes directly from you. In some cases we also receive data relating to you from third parties:`,
         `from the carrier and the container tracking service — shipment events, container and bill of lading status;`,
         `from Google — email, name and profile picture, only if you choose to sign in with Google;`,
         `from Stripe — the result, status and reference of your payment (but not your card details);`,
         `from our logistics, customs and Korean partners — the data needed for your particular order and shipment.`,
         `The categories of that data and the legal bases for processing it are the same as those described in this policy.`]],
      ["4. Whether providing the data is obligatory",
        [`Providing some of the data is necessary in order to enter into and perform our contract with you, or to comply with the law:`,
         `without an email and a password we cannot create and maintain an account;`,
         `without a name, address and phone we cannot process an order, the import and delivery;`,
         `without payment details Stripe cannot accept a deposit or a payment.`,
         `If you do not provide that data we will not be able to provide you with the service in question. All other data (for example preferences and optional fields) is entirely voluntary, and refusing it does not affect your access to the main service.`]],
      ["5. Why, and on what legal basis, we process the data",
        [`Performance of a contract or steps before it (Art. 6(1)(b) GDPR): registering and maintaining your account, handling an enquiry, the order, the deposit, the import, tracking and delivery.`,
         `Legal obligation (Art. 6(1)(c)): accounting and tax records, customs paperwork, anti-money-laundering duties where they apply.`,
         `Legitimate interests (Art. 6(1)(f)): site security and fraud prevention, keeping records to defend ourselves in a dispute, technical maintenance and fixing faults. We have assessed that these purposes do not unduly override your rights; you can ask for a summary of that assessment at ${COMPANY.email} and object at any time (see section 10).`,
         `Consent (Art. 6(1)(a)): cookies and similar technologies that are not strictly necessary, personalised suggestions, and email or push alerts for a price drop or a new car matching a saved search. Consent can be withdrawn at any time — from "Cookie settings" in the footer or from your account — without affecting the lawfulness of processing before withdrawal.`]],
      ["6. Cookies and similar technologies",
        [`We write nothing to, and read nothing from, your device beyond the strictly necessary before you have given explicit consent for that category. Refusing is as easy as accepting, and the toggles start switched off.`,
         `The full list of names, purposes and lifetimes is in the Cookie policy. If we ever enable third-party statistics (Google Analytics 4) it will load only after consent to the "Statistics" category, with consent denied by default (Consent Mode) and with no advertising signals.`]],
      ["7. Who we share the data with",
        [`We share data only as far as necessary, and with the following categories of recipient:`,
         `Hosting and infrastructure: Hetzner Online GmbH, servers in Germany (processor).`,
         `Email: Resend (transactional messages — confirmations, alerts, replies to enquiries).`,
         `Payments: Stripe Payments Europe — an independent controller for your card data; we receive only the outcome of the payment.`,
         `Translation of listing text: Anthropic and Google. Only listing data is sent (make, model, the dealer's description), never your personal data.`,
         `Google sign-in: Google Ireland Ltd, only if you choose that way in. We receive your email, name and profile picture.`,
         `Shipment tracking: the carrier (e.g. Maersk) and the container tracking service we work with.`,
         `Logistics and import: freight forwarders, carriers, customs agents, port operators and our Korean partners, as far as your order requires.`,
         `Professional advisers: our accountant and, where needed, a lawyer or auditor, all bound by confidentiality.`,
         `Public authorities, where the law requires it.`,
         `With every provider that processes personal data on our behalf we have concluded a contract under Art. 28 GDPR obliging it to process the data only on our instructions, to guarantee confidentiality and appropriate technical and organisational measures, and to delete or return the data when the service ends. Independent controllers (e.g. Stripe, Google) process your data under their own privacy policies.`,
         `We do not sell personal data and we do not pass it to advertising networks.`]],
      ["8. Transfers outside the EU/EEA",
        [`Some of our providers (Anthropic, Google, Stripe) and our partners in South Korea are outside the EEA. Transfers take place on the basis of a European Commission adequacy decision where one exists for that recipient (including the EU–US Data Privacy Framework), and otherwise on the basis of Standard Contractual Clauses under Art. 46(2)(c) GDPR, accompanied by supplementary measures where needed.`,
         `To Korean partners and carriers we send only the minimum a specific purchase and shipment requires. Data sent for translation contains no personal information. You can request a copy of the applicable safeguards at ${COMPANY.email}.`]],
      ["9. How long we keep the data",
        [`Accounting ledgers and financial statements: 10 years, counted from 1 January of the year following the year in which they were drawn up. Other accounting and tax documents are kept for the periods set by Bulgarian accounting and tax law according to their type.`,
         `Account and address: for as long as you keep the account. On deletion we remove the account, the address, sessions, passkeys and two-factor secrets; only documents we are legally obliged to keep remain.`,
         `Enquiries that did not lead to a transaction: up to 2 years from the last correspondence.`,
         `Sessions: up to 30 days from the last activity. Technical records and logs: up to 90 days.`,
         `Consent record: 12 months (after which we ask again) and up to 3 years as proof that consent was given or refused.`,
         `Preference cookie: 90 days from the last activity; clearing your cookies removes it immediately.`]],
      ["10. Your rights",
        [`In relation to your personal data you have the right to: access and a copy of the data (Art. 15); rectification (Art. 16); erasure (Art. 17); restriction of processing (Art. 18); portability in a machine-readable format (Art. 20); objection to processing based on legitimate interests (Art. 21(1)); and withdrawal of consent at any time — from "Cookie settings" in the footer, the relevant toggles in your account, or an email to us.`,
         `If we ever send direct marketing messages, you have an unconditional right to object at any time and without giving a reason; after an objection we stop those messages (Art. 21(2)-(3)).`,
         `Requests are free of charge; send them to ${COMPANY.email}. We may ask for further information to satisfy ourselves that the request comes from you. We reply within the deadlines in section 1.`,
         `You have the right to complain to the Commission for Personal Data Protection, 2 Prof. Tsvetan Lazarov Blvd, Sofia 1592, kzld.bg. If you are in Romania — to ANSPDCP (dataprotection.ro), or to the supervisory authority where you live.`]],
      ["11. Automated decision-making and profiling",
        [`The "Relevant" ranking and the car suggestions are based on general search criteria and on the preferences you have entered or browsed yourself. They are only an aid to searching, produce no legal effects for you and do not similarly significantly affect you, so they do not amount to automated decision-making or profiling within the meaning of Art. 22 GDPR. They do not change the price you see or the terms you are offered.`]],
      ["12. Children",
        [`The service is intended for people over 18. We do not knowingly collect children's data. If we learn that we have received any, we delete it.`]],
      ["13. Security",
        [`All traffic is encrypted (HTTPS). Passwords are stored only as an Argon2id hash. Sessions are server-side behind an HttpOnly cookie and can be revoked from your account at any time; we offer two-factor authentication and passkeys. Access to data is limited to the people who need it for their work. We take regular backups and keep an audit log of administrative actions.`,
         `In the event of a security breach that leads to a high risk to your rights, we will notify you and the Commission for Personal Data Protection within the deadlines in Art. 33-34 GDPR.`]],
      ["14. Changes to this policy",
        [`Every material change is reflected in the version number and the update date and — where it affects your consent — in a new version, in which case the consent banner will ask you again.`]],
      ["Note",
        [`This text was drafted in good faith and in detail, but it does not replace legal advice. Have a lawyer review it before you rely on it commercially.`]],
    ],
    PRIVACY_STAMP.en
  ),
  cookies: doc(
    "Cookie policy",
    `Nothing that is not strictly necessary is written to or read from your device before you have given explicit consent. Below is every means we use, what it is for, who places it and how long it lives.`,
    [
      ["1. What this policy covers, and on what basis",
        [`This policy covers every technology through which we store information on your device or gain access to information already stored — cookies, localStorage and sessionStorage, the application cache and similar identifiers. The rules apply equally to all of them, whatever their technical name.`,
         `Storage and access take place under Art. 5(3) of Directive 2002/58/EC (ePrivacy), transposed into Bulgarian law by the Electronic Communications Act. Where personal data is processed through these means, the processing rests on consent (Art. 6(1)(a) GDPR) for the optional categories, and on legitimate interests or performance of the contract (Art. 6(1)(f) and (b) GDPR) for the strictly necessary ones. Full information about the processing of personal data is in the Privacy policy.`,
         `Controller: ${COMPANY.name}, company number ${COMPANY.eik}, ${COMPANY.address}; ${COMPANY.email}; phone ${COMPANY.phone}.`]],
      ["2. How consent works",
        [`On your first visit we show a banner with three equal choices: "Reject all", "Settings" and "Accept all". All three buttons carry the same visual priority — the same size, contrast and placement.`,
         `The toggles for the optional categories are switched off by default. Consent is separate for each category — you can accept one and refuse the other.`,
         `Refusing is as easy as accepting and takes the same number of actions. We use no misleading design, no pre-ticked boxes and no cookie wall — refusing does not limit your access to the site or the services.`,
         `Continuing to browse, scrolling or closing the banner is not treated as consent. Until you make a choice, no optional means are loaded.`,
         `Your choice is recorded — categories, date and policy version — and kept for 12 months, after which we ask again, as we do whenever this policy changes materially. The record proving that consent was given or refused is kept for up to 3 years as evidence under Art. 7(1) GDPR.`,
         `You can change or withdraw your choice at any time from "Cookie settings" in the footer of every page. On refusal or withdrawal the relevant means are deleted immediately; withdrawal does not affect the lawfulness of processing before it.`]],
      ["3. Strictly necessary (no consent needed)",
        [`encar_session — keeps you signed in. HttpOnly and unreachable by scripts, Secure (HTTPS only) and SameSite=Lax, which is what protects your requests from being forged by another site (CSRF) — we use no separate token for that. Deleted when you sign out. Cookie, ours · up to 30 days from the last activity.`,
         `ab_consent — records your cookie choice itself. It is necessary because it also stores a refusal — without it the banner would ask you again on every load. Cookie, ours · 12 months.`,
         `encar.lang / encar.currency / encar.theme — the language, currency and light/dark theme you chose. localStorage, ours · until you delete it.`,
         `encar.favourites / encar.searches — for visitors without an account: the cars and searches you saved yourself on your own device. localStorage, ours · until you delete them.`,
         `Technical cache (encar.cms.* and the application cache) — a cache of page copy so it is not re-fetched on every visit. It holds no personal data and identifies no device. Cache, ours · until the cache is cleared.`,
         `These means are strictly necessary to run the site and the service you asked for, so the law does not require consent for them. They cannot be switched off in the settings, but you can block them in your browser (see section 9).`]],
      ["4. Personalisation (with consent)",
        [`ab_taste — which makes, models and fuels you browse, so we can order the cars that suit you. Cookie, ours · 90 days.`,
         `ab_vid — a random browser identifier tied to that same preference profile. It carries no name or email. Cookie, ours · 90 days.`,
         `ab_track — the references you have already looked up on Track my vehicle, so you do not retype them. Cookie, ours · 90 days.`,
         `This data serves only to order search results. It produces no legal effects for you, does not change the price you see or the terms you are offered, and does not amount to profiling within the meaning of Art. 22 GDPR.`]],
      ["5. Statistics (with consent)",
        [`Listing view counter — sent to our own server so we know which cars people are looking for. It writes no cookie on your device and is not linked to your account. Server-side event, ours · aggregated, no identifier.`,
         `The counter runs entirely on our own server and neither stores nor reads information from your device, but we still place it under consent to give you full control. We use the results only in aggregate.`,
         `If we enable Google Analytics 4 in future it will load only after consent to this category, with permissions denied by default (Google Consent Mode v2), IP anonymisation on and no advertising signals. As at the date of this version it is not active and no Google script is loaded for statistical purposes.`]],
      ["6. Third-party means at payment and sign-in",
        [`When you start a payment yourself or choose to sign in with Google, that provider may place its own cookies on your device. They are necessary for the service you asked for and for fraud prevention:`,
         `Stripe Payments Europe — cookies for processing the payment and detecting fraud. They load only on the payment and deposit pages. Stripe acts as an independent controller; its terms are at stripe.com/privacy.`,
         `Google Ireland Ltd — authentication cookies, only if you choose to sign in with Google. Its terms are at policies.google.com/privacy.`,
         `If you do not use those features, no third-party means are loaded at all. We have no control over the lifetimes of cookies placed by these providers — the current lifetimes are in their own policies.`]],
      ["7. Marketing and advertising",
        [`We use none. No ad networks, no retargeting, no third-party pixels or scripts for advertising purposes, and no selling or swapping of data with advertisers. That is why there is no "Marketing" category in the settings — there is nothing to switch on or off.`]],
      ["8. What happens if you refuse",
        [`The site works fully: browsing, searching, registering, ordering, paying and tracking all remain available.`,
         `We will not order suggestions around your interests, and you will see the general ranking.`,
         `You will retype the references on Track my vehicle.`,
         `We will not count your listing views in the statistics.`]],
      ["9. Managing and deleting them in your browser",
        [`Besides "Cookie settings" you can delete or block these means in your browser. Local storage (localStorage) is cleared by deleting the site's data, not only its cookies.`,
         `Chrome: Settings → Privacy and security → Cookies and other site data.`,
         `Safari: Settings → Privacy → Manage website data.`,
         `Firefox: Settings → Privacy & Security → Cookies and Site Data.`,
         `Edge: Settings → Cookies and site permissions.`,
         `Blocking the strictly necessary means may break signing in and the saving of your cookie choice. Browser-level privacy signals (Do Not Track, Global Privacy Control) have no legal effect in the EU today and do not replace your choice in the banner — the choice you make in "Cookie settings" is what governs.`]],
      ["10. Your rights and the link to personal data",
        [`Where personal data is processed through the means described here, you have every right the GDPR gives you — access, rectification, erasure, restriction, portability, objection and withdrawal of consent. How to exercise them and our response times are in the Privacy policy.`,
         `You have the right to complain to the Commission for Personal Data Protection, 2 Prof. Tsvetan Lazarov Blvd, Sofia 1592, kzld.bg, or to the supervisory authority where you live.`]],
      ["11. Children",
        [`The service is intended for people over 18. We do not knowingly place personalisation or statistics means on children's devices.`]],
      ["12. Changes to this policy",
        [`Every material change is reflected in the version number and the update date. Where a change affects the categories you consented to, the banner will ask you again and your previous choice will not carry over automatically.`]],
      ["13. Questions",
        [`Write to ${COMPANY.email}. How we handle personal data is set out in the Privacy policy.`]],
      ["Note",
        [`This text was drafted in good faith and in detail, but it does not replace legal advice. Have a lawyer review it before you rely on it commercially.`]],
    ],
    PRIVACY_STAMP.en
  ),
  contact: doc(
    "Contact and company details",
    `This site is operated by ${COMPANY.name}.`,
    [
      ["Company details",
        [`Name: ${COMPANY.name}`, `Company number: ${COMPANY.eik}`, `Address: ${COMPANY.address}`,
         `Phone: ${COMPANY.phone}`, `Country of registration: Bulgaria`]],
      ["Reach us",
        [`Email: ${COMPANY.email}`, `We answer within two working days.`]],
      ["Complaints",
        [`If we have not resolved your issue, you can turn to the Bulgarian consumer protection commission.`]],
    ]
  ),
};

return { bg: BG, ro: RO, en: EN };
}

let cache = null;
let cacheKey = "";

function docs() {
  const key = JSON.stringify(COMPANY);
  if (!cache || cacheKey !== key) {
    cache = build();
    cacheKey = key;
  }
  return cache;
}

export function legalDoc(lang, slug) {
  const DOCS = docs();
  const table = DOCS[lang] || DOCS.bg;
  return table[slug] || table.terms;
}
