import { COMPANY } from "@/content/company";

/**
 * The site's legal documents, in all three languages.
 *
 * Written for this business specifically: we buy cars at Korean auction/dealer level, quote
 * one landed price, ship them by sea and deliver to the buyer's address. The documents say
 * exactly that, and nothing they cannot back up. They are a starting point drafted in good
 * faith, NOT legal advice — the owner should have a Bulgarian lawyer review them before
 * relying on them commercially, which the pages themselves say.
 */
const UPDATED = "2026-06-08";

const doc = (title, intro, sections) => ({ title, intro, sections, updated: UPDATED });

// Built on demand rather than at import time: the company details can be edited in the
// admin, and these documents quote them.
function build() {

const BG = {
  terms: doc(
    "Общи условия",
    `Тези условия уреждат използването на ${COMPANY.site} и поръчката на автомобил чрез ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
    [
      ["Какво правим",
        [`Показваме автомобили, обявени за продажба в Южна Корея, преведени на български, румънски и английски.`,
         `Цената, която виждаш, е крайна прогнозна цена до твоя адрес: включва автомобила, морския транспорт, мито и ДДС, освен ако на страницата на обявата не е посочено друго.`]],
      ["Обявите не са наша собственост",
        [`Данните и снимките идват от корейския пазар и се обновяват периодично. Възможно е автомобил да бъде продаден или свален от продажба, преди да получим обновени данни.`,
         `Затова обява на сайта е покана за запитване, а не обвързваща оферта. Обвързваща цена получаваш в писмено потвърждение от нас.`]],
      ["Поръчка и плащане",
        [`След запитване потвърждаваме наличността, окончателната цена и срока, и издаваме документ за плащане. Договорът се счита сключен, когато потвърдим поръчката писмено.`,
         `Плащането се извършва по банков път към ${COMPANY.name}. Не приемаме плащания в брой за автомобили.`]],
      ["Срокове и доставка",
        [`Ориентировъчният срок от потвърдена поръчка до доставка е между 6 и 10 седмици и зависи от корабните разписания, пристанищните и митническите процедури.`,
         `Датите в раздел „Проследи автомобила“ са прогнозни. Последната стъпка — доставка до твоя адрес — се изчислява като приблизително седем дни след пристигане в европейското пристанище.`]],
      ["Състояние на автомобила",
        [`Автомобилите са употребявани. Показваме инспекционния доклад и историята, доколкото са налични от източника.`,
         `Употребяван автомобил може да има износване, което не е отразено в документите. При съмнение поискай допълнителна проверка преди да поръчаш.`]],
      ["Право на отказ",
        [`Ако си потребител по смисъла на българското законодателство, имаш законовите си права, включително право на отказ, когато то е приложимо за конкретната сделка.`,
         `Автомобил, поръчан и внесен по твоя изрична индивидуална заявка, може да попада в изключенията от правото на отказ. Ще ти посочим кое важи за твоята поръчка, преди да платиш.`]],
      ["Отговорност",
        [`Не отговаряме за забави, причинени от превозвачи, пристанища, митници или органи, извън нашия контрол, но те винаги ти се съобщават веднага щом ги узнаем.`,
         `Не отговаряме за косвени вреди, като пропуснати ползи или разходи за наем на друг автомобил.`]],
      ["Спорове",
        [`Прилага се българското право. Спорове се решават от компетентния български съд, освен ако задължителна потребителска норма не предвижда друго.`,
         `Можеш да се обърнеш и към Комисията за защита на потребителите или към платформата за онлайн решаване на спорове на Европейската комисия.`]],
      ["Контакт",
        [`Пиши ни на ${COMPANY.email}. Отговаряме в рамките на два работни дни.`]],
    ]
  ),
  privacy: doc(
    "Политика за поверителност",
    `${COMPANY.name}, ЕИК ${COMPANY.eik}, със седалище ${COMPANY.address}, е администратор на личните данни, обработвани през ${COMPANY.site}. Тази политика обяснява какви данни събираме, на какво основание, с кого ги споделяме, колко дълго ги пазим и как упражняваш правата си по Общия регламент (ЕС) 2016/679 (GDPR).`,
    [
      ["Кой отговаря за данните ти",
        [`Администратор: ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
         `Адрес: ${COMPANY.address}.`,
         `Имейл за всички въпроси и заявки по GDPR: ${COMPANY.email}. Телефон: ${COMPANY.phone}.`,
         `Не сме длъжни да определяме длъжностно лице по защита на данните. Заявките се обработват от управителя и получаваш отговор до един месец (при сложни случаи срокът може да се удължи с още два месеца, за което ще те уведомим).`]],
      ["Какви данни обработваме",
        [`Профил: имейл, име (ако го попълниш), парола — съхранявана само като необратим хеш (Argon2id) — и данни за двуфакторна защита или passkey, ако си я включил.`,
         `Данни за доставка и фактуриране: име, улица, град, пощенски код, държава и телефон — само ако ги въведеш.`,
         `Запитвания и кореспонденция: съобщението, имейлът и телефонът, които ни изпращаш, и отговорите ни.`,
         `Плащания и депозити: сума, статус, дата и идентификатор на плащането. Данните на картата ти се въвеждат директно при Stripe — ние никога не виждаме и не съхраняваме номер на карта.`,
         `Пратки: номера на товарителници и контейнери, свързани с твоята поръчка, събитията от превозвача и държавата за последната стъпка от доставката.`,
         `Технически данни: IP адрес, тип браузър и устройство, време на заявката и записи за вход/изход от профила (включително списък на активните сесии, който виждаш в профила си).`,
         `Записът за съгласието ти: кои категории бисквитки си приел или отказал, кога и срещу коя версия на политиката.`,
         `Предпочитания (само със съгласие): кои марки, модели и горива разглеждаш, в бисквитка на твоето устройство със срок 90 дни.`]],
      ["Защо и на какво правно основание",
        [`Изпълнение на договор или преддоговорни действия (чл. 6, § 1, б. „б“ GDPR): регистрация и поддръжка на профила, обработка на запитване, поръчка, депозит, внос, проследяване и доставка.`,
         `Законово задължение (чл. 6, § 1, б. „в“): счетоводна и данъчна отчетност, митнически документи, задължения по Закона за мерките против изпирането на пари, когато са приложими.`,
         `Легитимен интерес (чл. 6, § 1, б. „е“): сигурност на сайта и предотвратяване на измами, поддържане на записи за защита при спор, техническа поддръжка и отстраняване на грешки. Преценили сме, че тези цели не накърняват неоправдано правата ти, и можеш да възразиш по всяко време.`,
         `Съгласие (чл. 6, § 1, б. „а“): бисквитки и подобни технологии, които не са строго необходими, персонализирани предложения, известия по имейл и push за спад в цената или нова кола по запазено търсене. Съгласието се оттегля по всяко време — от „Настройки за бисквитки“ във футъра или от профила — без това да засяга законосъобразността на обработването преди оттеглянето.`]],
      ["Бисквитки и подобни технологии",
        [`Не записваме и не четем нищо на твоето устройство извън строго необходимото, преди да си дал изрично съгласие за съответната категория. Отказът е толкова лесен, колкото приемането, и превключвателите са изключени по подразбиране.`,
         `Пълният списък с имена, цели и срокове е в Политиката за бисквитките. Ако някога включим статистика от трета страна (Google Analytics 4), тя ще се зарежда само след съгласие за категория „Статистика“, с отказано по подразбиране съгласие (Consent Mode) и без рекламни сигнали.`]],
      ["С кого споделяме данните",
        [`Хостинг и инфраструктура: Hetzner Online GmbH, сървъри в Германия (обработващ лични данни).`,
         `Имейли: Resend (транзакционни съобщения — потвърждения, известия, отговори на запитвания).`,
         `Плащания: Stripe Payments Europe — самостоятелен администратор за данните на картата ти; ние получаваме само резултата от плащането.`,
         `Превод на текстовете от обявите: Anthropic и Google. Изпращат се само данни от обявата (марка, модел, описание от търговеца), никога твои лични данни.`,
         `Вход с Google: Google Ireland Ltd, само ако сам избереш този начин на вход. Получаваме имейл, име и профилна снимка.`,
         `Проследяване на пратки: превозвачът (напр. Maersk) и услугата за проследяване на контейнери, с която работим.`,
         `Логистика и внос: спедитори, превозвачи, митнически агенти, пристанищни оператори и корейските ни партньори, доколкото е нужно за твоята поръчка.`,
         `Професионални консултанти: счетоводител, а при нужда адвокат или одитор, обвързани с поверителност.`,
         `Държавни органи, когато законът го изисква. Не продаваме лични данни и не ги предоставяме на рекламни мрежи.`]],
      ["Предаване извън ЕС/ЕИП",
        [`Част от доставчиците ни (Anthropic, Google, Stripe) и партньорите ни в Южна Корея се намират извън ЕИП. Предаването се извършва въз основа на решение на Европейската комисия за адекватно ниво на защита, когато има такова (включително рамката EU–US Data Privacy Framework), а в останалите случаи — въз основа на стандартни договорни клаузи по чл. 46, § 2, б. „в“ GDPR.`,
         `Към корейските партньори и превозвачите изпращаме само минимума, нужен за конкретната покупка и превоз. Данни за превод не съдържат лична информация.`,
         `Копие от приложимите гаранции можеш да поискаш на ${COMPANY.email}.`]],
      ["Колко дълго пазим данните",
        [`Счетоводни и данъчни документи: 10 години след годината на издаване (Закон за счетоводството, ДОПК).`,
         `Профил и адрес: докато поддържаш профила. При изтриване премахваме профила, адреса, сесиите, passkeys и двуфакторните тайни; остават само документите, които сме длъжни да пазим.`,
         `Запитвания без сключена сделка: до 2 години от последната кореспонденция.`,
         `Сесии: до 30 дни от последната активност. Технически записи и логове: до 90 дни.`,
         `Запис за съгласие: 12 месеца (след което питаме отново) и до 3 години като доказателство, че съгласието е било дадено или отказано.`,
         `Бисквитка с предпочитания: 90 дни от последната активност; изтриването на бисквитките я премахва веднага.`]],
      ["Твоите права",
        [`Достъп до данните и копие от тях (чл. 15), коригиране (чл. 16), изтриване (чл. 17), ограничаване на обработването (чл. 18), преносимост в машинно четим формат (чл. 20) и възражение срещу обработване на основание легитимен интерес (чл. 21).`,
         `Оттегляне на съгласие по всяко време — „Настройки за бисквитки“ във футъра на всяка страница, съответните превключватели в профила или имейл до нас.`,
         `Заявките са безплатни; изпрати ги на ${COMPANY.email}. Може да поискаме допълнителна информация, за да се уверим, че заявката е от теб.`,
         `Право на жалба до Комисията за защита на личните данни, гр. София 1592, бул. „Проф. Цветан Лазаров“ № 2, kzld.bg. Ако си в Румъния — до ANSPDCP (dataprotection.ro), или до надзорния орган по местоживеенето ти.`]],
      ["Автоматизирано вземане на решения",
        [`Не вземаме решения с правни последици за теб само по автоматизиран начин и не извършваме профилиране по смисъла на чл. 22 GDPR.`,
         `Подредбата „Подходящи“ и предложенията за автомобили са единствено помощ при търсенето. Те не влияят на цената, която виждаш, нито на условията, които получаваш.`]],
      ["Деца",
        [`Услугата е предназначена за лица над 18 години. Не събираме съзнателно данни на деца. Ако разберем, че сме получили такива, ги изтриваме.`]],
      ["Сигурност",
        [`Целият трафик е криптиран (HTTPS). Паролите се съхраняват само като Argon2id хеш. Сесиите са сървърни, с HttpOnly бисквитка, и могат да се прекратят от профила ти по всяко време; предлагаме двуфакторна защита и passkeys.`,
         `Достъпът до данните е ограничен до лицата, които го изискват за работата си. Правим редовни резервни копия и водим одитен дневник на административните действия.`,
         `При нарушение на сигурността, което води до висок риск за правата ти, ще те уведомим и ще уведомим КЗЛД в срока по чл. 33–34 GDPR.`]],
      ["Промени в политиката",
        [`Всяка съществена промяна се отразява в датата на актуализация и — когато засяга съгласието — в нова версия, при която банерът ще те попита отново.`]],
      ["Бележка",
        [`Този текст е изготвен добросъвестно и подробно, но не замества юридическа консултация. Преди да разчиташ на него търговски, дай го за преглед на адвокат.`]],
    ]
  ),
  cookies: doc(
    "Политика за бисквитките",
    `Нищо, което не е строго необходимо, не се записва и не се чете от твоето устройство, преди да си дал изрично съгласие. По-долу е всяка бисквитка и всяко подобно средство, което използваме, за какво служи и колко живее.`,
    [
      ["Как работи съгласието",
        [`При първото посещение показваме банер с три равнопоставени избора: „Отказвам всички“, „Настройки“ и „Приемам всички“. Превключвателите за незадължителните категории са изключени по подразбиране.`,
         `Изборът се записва като запис — категории, дата и версия на политиката — за 12 месеца. След това питаме отново, както и при съществена промяна на тази политика.`,
         `Можеш да промениш или оттеглиш избора си по всяко време от „Настройки за бисквитки“ във футъра на всяка страница. При отказ съответните бисквитки се изтриват веднага.`]],
      ["Строго необходими (без съгласие)",
        [`encar_session — държи те влязъл в профила. HttpOnly, срок 30 дни; изтрива се при изход.`,
         `ab_consent — самият твой избор за бисквитките. Срок 12 месеца. Пази и отказ, затова е необходима.`,
         `Локално в браузъра (localStorage): избраният език, валута и тема (светла/тъмна), а за посетители без профил — запазените коли и търсения, които сам си запазил, докато не ги изтриеш.`,
         `Технически кеш на текстовете и страниците, за да не се презареждат при всяко отваряне. Не съдържа лични данни и не идентифицира устройството.`,
         `Тези средства са необходими, за да работи сайтът и услугата, която сам поиска, затова законът не изисква съгласие за тях.`]],
      ["Персонализация (със съгласие)",
        [`ab_taste — кои марки, модели и горива разглеждаш, за да подредим подходящите автомобили. Срок 90 дни.`,
         `ab_vid — случаен идентификатор на браузъра, свързан със същия профил на предпочитания. Не съдържа име или имейл. Срок 90 дни.`,
         `ab_track — номерата, които вече си проверявал в „Проследи автомобила“, за да не ги въвеждаш отново. Срок 90 дни.`,
         `Ако откажеш, сайтът работи напълно — просто не подреждаме предложенията по твоите интереси.`]],
      ["Статистика (със съгласие)",
        [`Брояч на отваряния на обява: изпраща се към нашия сървър, за да знаем кои автомобили се търсят. Не записва бисквитка на устройството ти и не се свързва с профил.`,
         `Ако в бъдеще включим Google Analytics 4, той ще се зарежда само след съгласие за тази категория, с отказани по подразбиране разрешения (Google Consent Mode), с анонимизиран IP и без рекламни сигнали. Днес не е активен и никакъв скрипт на Google не се зарежда.`]],
      ["Маркетинг и реклама",
        [`Не използваме. Няма рекламни мрежи, няма ретаргетинг, няма пиксели на трети страни и няма продажба или обмен на данни с рекламодатели.`]],
      ["Изтриване от браузъра",
        [`Освен от нашите настройки можеш да изтриеш или блокираш бисквитките и от настройките на браузъра си. Блокирането на строго необходимите може да наруши входа в профила.`]],
      ["Въпроси",
        [`Пиши на ${COMPANY.email}. Как обработваме личните данни е описано в Политиката за поверителност.`]],
    ]
  ),
  contact: doc(
    "Контакт и данни за фирмата",
    `Сайтът се управлява от ${COMPANY.name}.`,
    [
      ["Фирмени данни",
        [`Наименование: ${COMPANY.name}`, `ЕИК: ${COMPANY.eik}`, `Адрес: ${COMPANY.address}`,
         `Телефон: ${COMPANY.phone}`, `Държава на регистрация: България`]],
      ["Връзка с нас",
        [`Имейл: ${COMPANY.email}`, `Отговаряме в рамките на два работни дни.`]],
      ["Жалби",
        [`Ако не сме решили въпроса ти, можеш да се обърнеш към Комисията за защита на потребителите.`]],
    ]
  ),
};

const RO = {
  terms: doc(
    "Termeni și condiții",
    `Acești termeni reglementează folosirea site-ului ${COMPANY.site} și comanda unei mașini prin ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
    [
      ["Ce facem",
        [`Afișăm mașini scoase la vânzare în Coreea de Sud, traduse în bulgară, română și engleză.`,
         `Prețul afișat este prețul final estimat până la adresa ta: mașina, transportul maritim, taxele vamale și TVA, dacă pagina anunțului nu spune altfel.`]],
      ["Anunțurile nu ne aparțin",
        [`Datele și fotografiile provin din piața coreeană și se actualizează periodic. O mașină poate fi vândută înainte să primim date noi.`,
         `De aceea un anunț este o invitație la cerere, nu o ofertă obligatorie. Prețul obligatoriu îl primești în confirmarea noastră scrisă.`]],
      ["Comandă și plată",
        [`După cerere confirmăm disponibilitatea, prețul final și termenul, apoi emitem documentul de plată. Contractul se încheie când confirmăm comanda în scris.`,
         `Plata se face prin transfer bancar către ${COMPANY.name}. Nu acceptăm numerar pentru mașini.`]],
      ["Termene și livrare",
        [`Termenul orientativ de la comanda confirmată până la livrare este de 6-10 săptămâni și depinde de orarele navelor și de procedurile portuare și vamale.`,
         `Datele din „Urmărește mașina” sunt estimări. Ultimul pas — livrarea la adresa ta — se calculează la aproximativ șapte zile după sosirea în portul european.`]],
      ["Starea mașinii",
        [`Mașinile sunt second-hand. Afișăm raportul de inspecție și istoricul, în măsura în care sursa le pune la dispoziție.`,
         `O mașină folosită poate avea uzură care nu apare în documente. Dacă ai dubii, cere o verificare suplimentară înainte de comandă.`]],
      ["Dreptul de retragere",
        [`Dacă ești consumator, îți păstrezi drepturile legale, inclusiv dreptul de retragere atunci când se aplică tranzacției tale.`,
         `O mașină adusă la cererea ta individuală expresă poate intra în excepțiile de la dreptul de retragere. Îți spunem ce se aplică înainte de plată.`]],
      ["Răspundere",
        [`Nu răspundem pentru întârzieri provocate de transportatori, porturi, vamă sau autorități, dar te informăm imediat ce le aflăm.`,
         `Nu răspundem pentru prejudicii indirecte, precum profit nerealizat sau costul închirierii altei mașini.`]],
      ["Litigii",
        [`Se aplică legea bulgară. Litigiile se soluționează de instanța bulgară competentă, dacă o normă imperativă de protecție a consumatorului nu prevede altfel.`,
         `Poți folosi și platforma europeană de soluționare online a litigiilor.`]],
      ["Contact",
        [`Scrie-ne la ${COMPANY.email}. Răspundem în două zile lucrătoare.`]],
    ]
  ),
  privacy: doc(
    "Politica de confidențialitate",
    `${COMPANY.name}, cod unic ${COMPANY.eik}, cu sediul în ${COMPANY.address}, este operatorul datelor personale prelucrate prin ${COMPANY.site}. Această politică explică ce date colectăm, în baza cărui temei, cu cine le împărtășim, cât le păstrăm și cum îți exerciți drepturile conform Regulamentului (UE) 2016/679 (GDPR).`,
    [
      ["Cine răspunde pentru datele tale",
        [`Operator: ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
         `Adresă: ${COMPANY.address}.`,
         `E-mail pentru orice întrebare și pentru cererile GDPR: ${COMPANY.email}. Telefon: ${COMPANY.phone}.`,
         `Nu avem obligația de a numi un responsabil cu protecția datelor. Cererile sunt tratate de administrator și primești răspuns în cel mult o lună (termen prelungibil cu două luni în cazuri complexe, cu informarea ta).`]],
      ["Ce date prelucrăm",
        [`Cont: e-mail, nume (dacă îl completezi), parola — păstrată doar ca hash ireversibil (Argon2id) — și datele pentru autentificarea în doi pași sau passkey, dacă le activezi.`,
         `Date de livrare și facturare: nume, stradă, oraș, cod poștal, țară și telefon — numai dacă le introduci.`,
         `Cereri și corespondență: mesajul, e-mailul și telefonul pe care ni le trimiți, plus răspunsurile noastre.`,
         `Plăți și depozite: sumă, stare, dată și identificatorul plății. Datele cardului se introduc direct la Stripe — noi nu vedem și nu stocăm niciodată numărul cardului.`,
         `Transporturi: numerele de conosament și de container legate de comanda ta, evenimentele de la transportator și țara folosită pentru ultimul pas al livrării.`,
         `Date tehnice: adresa IP, tipul de browser și dispozitiv, momentul cererii și înregistrările de autentificare (inclusiv lista sesiunilor active, pe care o vezi în cont).`,
         `Înregistrarea consimțământului: ce categorii de cookie-uri ai acceptat sau refuzat, când și față de ce versiune a politicii.`,
         `Preferințe (numai cu consimțământ): ce mărci, modele și combustibili deschizi, într-un cookie de pe dispozitivul tău, valabil 90 de zile.`]],
      ["De ce și în baza cărui temei",
        [`Executarea contractului sau demersuri precontractuale (art. 6 alin. 1 lit. b GDPR): crearea și administrarea contului, tratarea cererii, comanda, depozitul, importul, urmărirea și livrarea.`,
         `Obligație legală (art. 6 alin. 1 lit. c): contabilitate și fiscalitate, documente vamale, obligații privind prevenirea spălării banilor, când sunt aplicabile.`,
         `Interes legitim (art. 6 alin. 1 lit. f): securitatea site-ului și prevenirea fraudei, păstrarea dovezilor în caz de litigiu, mentenanță tehnică și remedierea erorilor. Am evaluat că aceste scopuri nu îți afectează în mod nejustificat drepturile și te poți opune oricând.`,
         `Consimțământ (art. 6 alin. 1 lit. a): cookie-uri și tehnologii similare care nu sunt strict necesare, recomandări personalizate, notificări prin e-mail și push pentru scăderi de preț sau mașini noi într-o căutare salvată. Consimțământul poate fi retras oricând — din „Setări cookie-uri” din footer sau din cont — fără a afecta legalitatea prelucrării anterioare.`]],
      ["Cookie-uri și tehnologii similare",
        [`Nu scriem și nu citim nimic pe dispozitivul tău în afara strictului necesar înainte să îți dai consimțământul explicit pentru categoria respectivă. Refuzul este la fel de simplu ca acceptarea, iar comutatoarele sunt dezactivate implicit.`,
         `Lista completă cu nume, scopuri și durate este în Politica de cookie-uri. Dacă vom activa vreodată statistici de la un terț (Google Analytics 4), acestea se vor încărca doar după consimțământ pentru categoria „Statistici”, cu permisiuni refuzate implicit (Consent Mode) și fără semnale publicitare.`]],
      ["Cu cine împărtășim datele",
        [`Găzduire și infrastructură: Hetzner Online GmbH, servere în Germania (persoană împuternicită).`,
         `E-mailuri: Resend (mesaje tranzacționale — confirmări, notificări, răspunsuri la cereri).`,
         `Plăți: Stripe Payments Europe — operator independent pentru datele cardului; noi primim doar rezultatul plății.`,
         `Traducerea textelor din anunțuri: Anthropic și Google. Se trimit doar date din anunț (marcă, model, descrierea dealerului), niciodată datele tale personale.`,
         `Autentificare cu Google: Google Ireland Ltd, doar dacă alegi tu această metodă. Primim e-mailul, numele și poza de profil.`,
         `Urmărirea transportului: transportatorul (de ex. Maersk) și serviciul de urmărire a containerelor cu care lucrăm.`,
         `Logistică și import: case de expediții, transportatori, agenți vamali, operatori portuari și partenerii noștri coreeni, cât este necesar pentru comanda ta.`,
         `Consultanți profesioniști: contabil și, la nevoie, avocat sau auditor, obligați la confidențialitate.`,
         `Autorități, când legea o cere. Nu vindem date personale și nu le oferim rețelelor de publicitate.`]],
      ["Transferuri în afara UE/SEE",
        [`Unii furnizori (Anthropic, Google, Stripe) și partenerii din Coreea de Sud se află în afara SEE. Transferul are loc pe baza unei decizii de adecvare a Comisiei Europene, când există (inclusiv EU–US Data Privacy Framework), iar în restul cazurilor pe baza clauzelor contractuale standard conform art. 46 alin. 2 lit. c GDPR.`,
         `Către partenerii coreeni și transportatori trimitem strict minimul necesar pentru achiziția și transportul respectiv. Datele trimise pentru traducere nu conțin informații personale.`,
         `O copie a garanțiilor aplicabile poate fi cerută la ${COMPANY.email}.`]],
      ["Cât păstrăm datele",
        [`Documente contabile și fiscale: 10 ani de la anul emiterii, conform legislației bulgare aplicabile.`,
         `Cont și adresă: cât timp păstrezi contul. La ștergere eliminăm contul, adresa, sesiunile, passkeys și secretele de autentificare în doi pași; rămân doar documentele pe care legea ne obligă să le păstrăm.`,
         `Cereri fără tranzacție: până la 2 ani de la ultima corespondență.`,
         `Sesiuni: până la 30 de zile de la ultima activitate. Jurnale tehnice: până la 90 de zile.`,
         `Înregistrarea consimțământului: 12 luni (după care întrebăm din nou) și până la 3 ani ca dovadă că a fost dat sau refuzat.`,
         `Cookie-ul de preferințe: 90 de zile de la ultima activitate; ștergerea cookie-urilor îl elimină imediat.`]],
      ["Drepturile tale",
        [`Acces și o copie a datelor (art. 15), rectificare (art. 16), ștergere (art. 17), restricționarea prelucrării (art. 18), portabilitate în format prelucrabil automat (art. 20) și opoziție față de prelucrarea bazată pe interes legitim (art. 21).`,
         `Retragerea consimțământului oricând — „Setări cookie-uri” în footer, comutatoarele din cont sau un e-mail către noi.`,
         `Cererile sunt gratuite; trimite-le la ${COMPANY.email}. Putem cere informații suplimentare pentru a ne asigura că cererea vine de la tine.`,
         `Dreptul de a depune plângere la ANSPDCP, B-dul G-ral. Gheorghe Magheru 28-30, București, dataprotection.ro, la Comisia bulgară pentru protecția datelor (kzld.bg) sau la autoritatea din țara ta de reședință.`]],
      ["Decizii automatizate",
        [`Nu luăm decizii cu efecte juridice asupra ta exclusiv prin mijloace automate și nu facem profilare în sensul art. 22 GDPR.`,
         `Sortarea „Potrivite” și recomandările sunt doar un ajutor la căutare. Nu influențează prețul afișat și nici condițiile pe care le primești.`]],
      ["Copii",
        [`Serviciul este destinat persoanelor peste 18 ani. Nu colectăm cu bună știință date ale copiilor. Dacă aflăm că am primit astfel de date, le ștergem.`]],
      ["Securitate",
        [`Tot traficul este criptat (HTTPS). Parolele sunt păstrate doar ca hash Argon2id. Sesiunile sunt pe server, cu cookie HttpOnly, și pot fi închise oricând din contul tău; oferim autentificare în doi pași și passkeys.`,
         `Accesul la date este limitat la persoanele care au nevoie de el. Facem copii de siguranță periodice și păstrăm un jurnal de audit al acțiunilor administrative.`,
         `În caz de încălcare a securității cu risc ridicat pentru drepturile tale, te informăm pe tine și autoritatea de supraveghere în termenele din art. 33–34 GDPR.`]],
      ["Modificări",
        [`Orice modificare importantă se reflectă în data actualizării și, când afectează consimțământul, într-o versiune nouă, caz în care bannerul te va întreba din nou.`]],
      ["Notă",
        [`Textul este redactat cu bună-credință și în detaliu, dar nu înlocuiește consultanța juridică. Cere avizul unui avocat înainte să te bazezi comercial pe el.`]],
    ]
  ),
  cookies: doc(
    "Politica de cookie-uri",
    `Nimic care nu este strict necesar nu se scrie și nu se citește de pe dispozitivul tău înainte să îți dai consimțământul explicit. Mai jos sunt toate cookie-urile și mijloacele similare pe care le folosim, la ce servesc și cât trăiesc.`,
    [
      ["Cum funcționează consimțământul",
        [`La prima vizită afișăm un banner cu trei opțiuni egale: „Refuz toate”, „Setări” și „Accept toate”. Comutatoarele categoriilor opționale sunt dezactivate implicit.`,
         `Alegerea se salvează ca înregistrare — categorii, dată și versiunea politicii — pentru 12 luni. Apoi întrebăm din nou, la fel ca la o modificare importantă a acestei politici.`,
         `Poți schimba sau retrage alegerea oricând din „Setări cookie-uri”, în footerul fiecărei pagini. La refuz, cookie-urile respective se șterg imediat.`]],
      ["Strict necesare (fără consimțământ)",
        [`encar_session — te menține autentificat. HttpOnly, 30 de zile; se șterge la deconectare.`,
         `ab_consent — chiar alegerea ta privind cookie-urile. 12 luni. Păstrează și un refuz, de aceea este necesar.`,
         `Local în browser (localStorage): limba, moneda și tema aleasă, iar pentru vizitatorii fără cont — mașinile și căutările salvate de tine, până le ștergi.`,
         `Cache tehnic al textelor și paginilor, ca să nu se reîncarce la fiecare deschidere. Nu conține date personale și nu identifică dispozitivul.`,
         `Aceste mijloace sunt necesare pentru funcționarea site-ului și a serviciului cerut de tine, deci legea nu impune consimțământ pentru ele.`]],
      ["Personalizare (cu consimțământ)",
        [`ab_taste — ce mărci, modele și combustibili deschizi, ca să ordonăm mașinile potrivite. 90 de zile.`,
         `ab_vid — un identificator aleatoriu al browserului, legat de același profil de preferințe. Nu conține nume sau e-mail. 90 de zile.`,
         `ab_track — numerele verificate deja în „Urmărește mașina”, ca să nu le reintroduci. 90 de zile.`,
         `Dacă refuzi, site-ul funcționează complet — doar nu ordonăm recomandările după interesele tale.`]],
      ["Statistici (cu consimțământ)",
        [`Contorul de deschideri ale unui anunț: se trimite către serverul nostru, ca să știm ce mașini se caută. Nu scrie un cookie pe dispozitivul tău și nu se leagă de cont.`,
         `Dacă vom activa în viitor Google Analytics 4, se va încărca doar după consimțământ pentru această categorie, cu permisiuni refuzate implicit (Google Consent Mode), IP anonimizat și fără semnale publicitare. Astăzi nu este activ și niciun script Google nu se încarcă.`]],
      ["Marketing și publicitate",
        [`Nu folosim. Fără rețele de publicitate, fără retargeting, fără pixeli ai terților și fără vânzarea sau schimbul de date cu advertiseri.`]],
      ["Ștergerea din browser",
        [`În plus față de setările noastre, poți șterge sau bloca cookie-urile din browserul tău. Blocarea celor strict necesare poate împiedica autentificarea.`]],
      ["Întrebări",
        [`Scrie la ${COMPANY.email}. Modul în care prelucrăm datele personale este descris în Politica de confidențialitate.`]],
    ]
  ),
  contact: doc(
    "Contact și date despre firmă",
    `Site-ul este administrat de ${COMPANY.name}.`,
    [
      ["Date despre firmă",
        [`Denumire: ${COMPANY.name}`, `Cod unic: ${COMPANY.eik}`, `Adresă: ${COMPANY.address}`,
         `Telefon: ${COMPANY.phone}`, `Țara de înregistrare: Bulgaria`]],
      ["Contact",
        [`E-mail: ${COMPANY.email}`, `Răspundem în două zile lucrătoare.`]],
      ["Reclamații",
        [`Dacă nu am rezolvat problema, te poți adresa autorității de protecție a consumatorului.`]],
    ]
  ),
};

const EN = {
  terms: doc(
    "Terms of service",
    `These terms cover the use of ${COMPANY.site} and ordering a car through ${COMPANY.name}, company number ${COMPANY.eik}.`,
    [
      ["What we do",
        [`We show cars offered for sale in South Korea, translated into Bulgarian, Romanian and English.`,
         `The price you see is the estimated final price to your address: the car, sea freight, customs duty and VAT, unless the listing page says otherwise.`]],
      ["The listings are not ours",
        [`Data and photos come from the Korean market and are refreshed periodically. A car can be sold before we receive updated data.`,
         `A listing is therefore an invitation to enquire, not a binding offer. A binding price comes in our written confirmation.`]],
      ["Ordering and payment",
        [`After your enquiry we confirm availability, the final price and the lead time, then issue the payment document. The contract is formed when we confirm your order in writing.`,
         `Payment is by bank transfer to ${COMPANY.name}. We do not accept cash for vehicles.`]],
      ["Lead times and delivery",
        [`From a confirmed order to delivery usually takes 6 to 10 weeks, depending on sailing schedules and on port and customs procedures.`,
         `Dates on the "Track my vehicle" page are estimates. The final step — delivery to your address — is calculated as roughly seven days after arrival at the European port.`]],
      ["Condition of the car",
        [`The cars are used. We show the inspection report and the history as far as the source makes them available.`,
         `A used car can have wear that the paperwork does not record. If in doubt, ask for an extra inspection before you order.`]],
      ["Right of withdrawal",
        [`If you are a consumer, you keep your statutory rights, including the right of withdrawal where it applies to your transaction.`,
         `A car imported on your express individual instruction may fall within the exceptions to that right. We will tell you which applies before you pay.`]],
      ["Liability",
        [`We are not liable for delays caused by carriers, ports, customs or authorities outside our control, but we always pass them on as soon as we learn of them.`,
         `We are not liable for indirect losses such as lost profit or the cost of hiring another car.`]],
      ["Disputes",
        [`Bulgarian law applies. Disputes go to the competent Bulgarian court, unless a mandatory consumer rule says otherwise.`,
         `You may also use the European Commission's online dispute resolution platform.`]],
      ["Contact",
        [`Write to ${COMPANY.email}. We answer within two working days.`]],
    ]
  ),
  privacy: doc(
    "Privacy policy",
    `${COMPANY.name}, company number ${COMPANY.eik}, registered at ${COMPANY.address}, is the controller of the personal data processed through ${COMPANY.site}. This policy explains what we collect, on what legal basis, who we share it with, how long we keep it and how you exercise your rights under Regulation (EU) 2016/679 (GDPR).`,
    [
      ["Who is responsible for your data",
        [`Controller: ${COMPANY.name}, company number ${COMPANY.eik}.`,
         `Address: ${COMPANY.address}.`,
         `Email for any question and for GDPR requests: ${COMPANY.email}. Phone: ${COMPANY.phone}.`,
         `We are not required to appoint a data protection officer. Requests are handled by the manager and answered within one month (extendable by two further months for complex requests, which we will tell you about).`]],
      ["What we process",
        [`Account: your email, your name if you give it, your password — kept only as an irreversible hash (Argon2id) — and two-factor or passkey data if you switch either on.`,
         `Delivery and billing details: name, street, city, post code, country and phone — only if you enter them.`,
         `Enquiries and correspondence: the message, email and phone you send us, and our replies.`,
         `Payments and deposits: amount, status, date and the payment reference. Card details are entered directly with Stripe — we never see or store a card number.`,
         `Shipments: the bill of lading and container numbers tied to your order, the carrier's events, and the country used for the final delivery step.`,
         `Technical data: IP address, browser and device type, request time and sign-in records (including the list of active sessions you can see in your account).`,
         `Your consent record: which cookie categories you accepted or refused, when, and against which version of this policy.`,
         `Preferences (only with consent): which makes, models and fuels you browse, in a cookie on your own device for 90 days.`]],
      ["Why, and on what legal basis",
        [`Performance of a contract or steps before it (Art. 6(1)(b) GDPR): creating and running your account, handling an enquiry, the order, the deposit, the import, tracking and delivery.`,
         `Legal obligation (Art. 6(1)(c)): accounting and tax records, customs paperwork, anti-money-laundering duties where they apply.`,
         `Legitimate interests (Art. 6(1)(f)): site security and fraud prevention, keeping records in case of a dispute, technical maintenance and fixing faults. We have weighed these against your rights and consider them proportionate; you can object at any time.`,
         `Consent (Art. 6(1)(a)): cookies and similar technologies that are not strictly necessary, personalised suggestions, and email or push alerts for price drops and new cars matching a saved search. Consent can be withdrawn at any time — from "Cookie settings" in the footer or from your account — without affecting the lawfulness of processing before withdrawal.`]],
      ["Cookies and similar technologies",
        [`We write nothing to, and read nothing from, your device beyond the strictly necessary before you have given explicit consent for that category. Refusing is as easy as accepting, and the toggles start switched off.`,
         `The full list of names, purposes and lifetimes is in the Cookie policy. If we ever enable third-party statistics (Google Analytics 4) it will load only after consent to the "Statistics" category, with Google Consent Mode defaults set to denied and no advertising signals.`]],
      ["Who we share it with",
        [`Hosting and infrastructure: Hetzner Online GmbH, servers in Germany (processor).`,
         `Email: Resend (transactional messages — confirmations, alerts, replies to enquiries).`,
         `Payments: Stripe Payments Europe — an independent controller for your card data; we receive only the outcome.`,
         `Translation of listing text: Anthropic and Google. Only listing data is sent (make, model, the dealer's description), never your personal data.`,
         `Google sign-in: Google Ireland Ltd, only if you choose that way in. We receive your email, name and profile picture.`,
         `Shipment tracking: the carrier (e.g. Maersk) and the container tracking service we use.`,
         `Logistics and import: freight forwarders, carriers, customs agents, port operators and our Korean partners, as far as your order requires.`,
         `Professional advisers: our accountant and, if needed, a lawyer or auditor, all under confidentiality.`,
         `Authorities, where the law requires it. We do not sell personal data and we do not pass it to advertising networks.`]],
      ["Transfers outside the EU/EEA",
        [`Some providers (Anthropic, Google, Stripe) and our partners in South Korea are outside the EEA. Transfers rely on a European Commission adequacy decision where one exists (including the EU–US Data Privacy Framework) and otherwise on Standard Contractual Clauses under Art. 46(2)(c) GDPR.`,
         `To Korean partners and carriers we send only the minimum a specific purchase and shipment needs. Data sent for translation contains no personal information.`,
         `You can ask for a copy of the safeguards at ${COMPANY.email}.`]],
      ["How long we keep it",
        [`Accounting and tax documents: 10 years after the year of issue, as Bulgarian accounting and tax law requires.`,
         `Account and address: for as long as you keep the account. On deletion we remove the account, the address, sessions, passkeys and two-factor secrets; only documents we are legally obliged to retain remain.`,
         `Enquiries that did not lead to a transaction: up to 2 years after the last correspondence.`,
         `Sessions: up to 30 days after the last activity. Technical logs: up to 90 days.`,
         `Consent record: 12 months (after which we ask again) and up to 3 years as proof that consent was given or refused.`,
         `Preference cookie: 90 days from the last activity; clearing your cookies removes it immediately.`]],
      ["Your rights",
        [`Access and a copy of your data (Art. 15), rectification (Art. 16), erasure (Art. 17), restriction (Art. 18), portability in a machine-readable format (Art. 20) and objection to processing based on legitimate interests (Art. 21).`,
         `Withdraw consent at any time — "Cookie settings" in the footer of every page, the toggles in your account, or an email to us.`,
         `Requests are free; send them to ${COMPANY.email}. We may ask for more information to be sure the request comes from you.`,
         `You can complain to the Bulgarian Commission for Personal Data Protection, 2 Prof. Tsvetan Lazarov Blvd, Sofia 1592, kzld.bg, to ANSPDCP in Romania (dataprotection.ro), or to the supervisory authority where you live.`]],
      ["Automated decision-making",
        [`We take no decisions with legal effect about you by automated means alone, and we do not carry out profiling within the meaning of Art. 22 GDPR.`,
         `The "Relevant" sort and the suggestions are search aids only. They do not change the price you see or the terms you are offered.`]],
      ["Children",
        [`The service is for people over 18. We do not knowingly collect children's data. If we learn that we have, we delete it.`]],
      ["Security",
        [`All traffic is encrypted (HTTPS). Passwords are kept only as an Argon2id hash. Sessions are server-side behind an HttpOnly cookie and can be revoked from your account at any time; two-factor authentication and passkeys are offered.`,
         `Access to data is limited to the people who need it for their work. We take regular backups and keep an audit log of administrative actions.`,
         `If a breach is likely to pose a high risk to your rights, we will inform you and the supervisory authority within the deadlines in Art. 33–34 GDPR.`]],
      ["Changes",
        [`Any material change is reflected in the update date and, where it affects consent, in a new version — in which case the banner will ask you again.`]],
      ["Note",
        [`This text was drafted in good faith and in detail, but it is not legal advice. Have a lawyer review it before you rely on it commercially.`]],
    ]
  ),
  cookies: doc(
    "Cookie policy",
    `Nothing that is not strictly necessary is written to or read from your device before you have given explicit consent. Below is every cookie and similar means we use, what it is for and how long it lives.`,
    [
      ["How consent works",
        [`On your first visit we show a banner with three equal choices: "Reject all", "Settings" and "Accept all". The toggles for the optional categories start switched off.`,
         `Your choice is stored as a record — categories, date and policy version — for 12 months. After that we ask again, as we do whenever this policy changes materially.`,
         `You can change or withdraw your choice at any time from "Cookie settings" in the footer of every page. On refusal the relevant cookies are deleted straight away.`]],
      ["Strictly necessary (no consent needed)",
        [`encar_session — keeps you signed in. HttpOnly, 30 days; deleted when you sign out.`,
         `ab_consent — your cookie choice itself. 12 months. It stores a refusal too, which is why it is necessary.`,
         `In your browser (localStorage): your chosen language, currency and light/dark theme, and for visitors without an account the cars and searches you saved yourself, until you delete them.`,
         `A technical cache of page copy so it is not re-fetched on every visit. It holds no personal data and identifies no device.`,
         `These are needed to run the site and the service you asked for, so the law does not require consent for them.`]],
      ["Personalisation (with consent)",
        [`ab_taste — which makes, models and fuels you browse, so we can order the cars that suit you. 90 days.`,
         `ab_vid — a random browser identifier tied to that same preference profile. It carries no name or email. 90 days.`,
         `ab_track — the references you have already looked up on Track my vehicle, so you do not retype them. 90 days.`,
         `If you refuse, the site still works fully — we simply do not order suggestions around your interests.`]],
      ["Statistics (with consent)",
        [`Listing view counter: sent to our own server so we know which cars people are looking for. It writes no cookie on your device and is not linked to an account.`,
         `If we enable Google Analytics 4 in future it will load only after consent to this category, with Google Consent Mode defaults denied, IP anonymisation on and no advertising signals. It is not active today and no Google script is loaded.`]],
      ["Marketing and advertising",
        [`We use none. No ad networks, no retargeting, no third-party pixels, and no selling or swapping of data with advertisers.`]],
      ["Clearing them in your browser",
        [`Besides our own settings you can delete or block cookies in your browser. Blocking the strictly necessary ones may stop you signing in.`]],
      ["Questions",
        [`Write to ${COMPANY.email}. How we handle personal data is set out in the Privacy policy.`]],
    ]
  ),
  contact: doc(
    "Contact and company details",
    `This site is operated by ${COMPANY.name}.`,
    [
      ["Company details",
        [`Name: ${COMPANY.name}`, `Company number: ${COMPANY.eik}`, `Address: ${COMPANY.address}`,
         `Phone: ${COMPANY.phone}`, `Country of registration: Bulgaria`]],
      ["Reach us",
        [`Email: ${COMPANY.email}`, `We answer within two working days.`]],
      ["Complaints",
        [`If we have not resolved your issue, you can turn to the Bulgarian consumer protection commission.`]],
    ]
  ),
};

return { bg: BG, ro: RO, en: EN };
}

let cache = null;
let cacheKey = "";

function docs() {
  const key = JSON.stringify(COMPANY);
  if (!cache || cacheKey !== key) {
    cache = build();
    cacheKey = key;
  }
  return cache;
}

export function legalDoc(lang, slug) {
  const DOCS = docs();
  const table = DOCS[lang] || DOCS.bg;
  return table[slug] || table.terms;
}
