import { COMPANY } from "@/content/company";

/**
 * The site's legal documents, in all three languages.
 *
 * Written for this business specifically: we buy cars at Korean auction/dealer level, quote
 * one landed price, ship them by sea and deliver to the buyer's address. The documents say
 * exactly that, and nothing they cannot back up. They are a starting point drafted in good
 * faith, NOT legal advice — the owner should have a Bulgarian lawyer review them before
 * relying on them commercially, which the pages themselves say.
 */
const UPDATED = "2026-06-08";

const doc = (title, intro, sections, updated = UPDATED) => ({
  title, intro, sections, updated,
});

// The owner's own privacy policy, as their lawyer settled it. Version and date come from that
// document rather than from UPDATED, so a change to another page cannot silently restamp it.
const PRIVACY_STAMP = {
  bg: "Версия 1.1 · Актуализирана на 6 август 2026 г.",
  ro: "Versiunea 1.1 · Actualizată la 6 august 2026",
  en: "Version 1.1 · Updated 6 August 2026",
};

// Built on demand rather than at import time: the company details can be edited in the
// admin, and these documents quote them.
function build() {

const BG = {
  terms: doc(
    "Общи условия",
    `Тези условия уреждат използването на ${COMPANY.site} и поръчката на автомобил чрез ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
    [
      ["Какво правим",
        [`Показваме автомобили, обявени за продажба в Южна Корея, преведени на български, румънски и английски.`,
         `Цената, която виждаш, е крайна прогнозна цена до твоя адрес: включва автомобила, морския транспорт, мито и ДДС, освен ако на страницата на обявата не е посочено друго.`]],
      ["Обявите не са наша собственост",
        [`Данните и снимките идват от корейския пазар и се обновяват периодично. Възможно е автомобил да бъде продаден или свален от продажба, преди да получим обновени данни.`,
         `Затова обява на сайта е покана за запитване, а не обвързваща оферта. Обвързваща цена получаваш в писмено потвърждение от нас.`]],
      ["Поръчка и плащане",
        [`След запитване потвърждаваме наличността, окончателната цена и срока, и издаваме документ за плащане. Договорът се счита сключен, когато потвърдим поръчката писмено.`,
         `Плащането се извършва по банков път към ${COMPANY.name}. Не приемаме плащания в брой за автомобили.`]],
      ["Срокове и доставка",
        [`Ориентировъчният срок от потвърдена поръчка до доставка е между 6 и 10 седмици и зависи от корабните разписания, пристанищните и митническите процедури.`,
         `Датите в раздел „Проследи автомобила“ са прогнозни. Последната стъпка — доставка до твоя адрес — се изчислява като приблизително седем дни след пристигане в европейското пристанище.`]],
      ["Състояние на автомобила",
        [`Автомобилите са употребявани. Показваме инспекционния доклад и историята, доколкото са налични от източника.`,
         `Употребяван автомобил може да има износване, което не е отразено в документите. При съмнение поискай допълнителна проверка преди да поръчаш.`]],
      ["Право на отказ",
        [`Ако си потребител по смисъла на българското законодателство, имаш законовите си права, включително право на отказ, когато то е приложимо за конкретната сделка.`,
         `Автомобил, поръчан и внесен по твоя изрична индивидуална заявка, може да попада в изключенията от правото на отказ. Ще ти посочим кое важи за твоята поръчка, преди да платиш.`]],
      ["Отговорност",
        [`Не отговаряме за забави, причинени от превозвачи, пристанища, митници или органи, извън нашия контрол, но те винаги ти се съобщават веднага щом ги узнаем.`,
         `Не отговаряме за косвени вреди, като пропуснати ползи или разходи за наем на друг автомобил.`]],
      ["Спорове",
        [`Прилага се българското право. Спорове се решават от компетентния български съд, освен ако задължителна потребителска норма не предвижда друго.`,
         `Можеш да се обърнеш и към Комисията за защита на потребителите или към платформата за онлайн решаване на спорове на Европейската комисия.`]],
      ["Контакт",
        [`Пиши ни на ${COMPANY.email}. Отговаряме в рамките на два работни дни.`]],
    ]
  ),
  privacy: doc(
    "Политика за поверителност",
    `${COMPANY.name}, ЕИК ${COMPANY.eik}, със седалище и адрес на управление ${COMPANY.address}, е администратор на личните данни, обработвани през ${COMPANY.site}. Тази политика обяснява какви данни събираме, на какво основание, откъде ги получаваме, с кого ги споделяме, колко дълго ги пазим и как упражняваш правата си по Общия регламент (ЕС) 2016/679 (GDPR) и Закона за защита на личните данни.`,
    [
      ["1. Кой отговаря за данните ти",
        [`Администратор: ${COMPANY.name}, ЕИК ${COMPANY.eik}.`,
         `Адрес: ${COMPANY.address}.`,
         `Контакт за въпроси и заявки по GDPR: ${COMPANY.email}; тел. ${COMPANY.phone}.`,
         `Не сме длъжни да определяме длъжностно лице по защита на данните и не сме определили такова. Заявките се обработват от управителя и получаваш отговор до един месец от получаването им. При сложни или многобройни заявки срокът може да се удължи с още два месеца, като ще те уведомим за удължаването и причините в рамките на първия месец.`]],
      ["2. Какви данни обработваме",
        [`Профил: имейл, име (ако го попълниш), парола — съхранявана само като необратим хеш (Argon2id) — и данни за двуфакторна защита или passkey, ако си я включил.`,
         `Доставка и фактуриране: име, улица, град, пощенски код, държава и телефон — само ако ги въведеш.`,
         `Запитвания и кореспонденция: съобщението, имейлът и телефонът, които ни изпращаш, и отговорите ни.`,
         `Плащания и депозити: сума, статус, дата и идентификатор на плащането. Данните на картата ти се въвеждат директно при Stripe — ние никога не виждаме и не съхраняваме номер на карта.`,
         `Пратки: номера на товарителници и контейнери, свързани с твоята поръчка, събитията от превозвача и държавата за последната стъпка от доставката.`,
         `Технически данни: IP адрес, тип браузър и устройство, време на заявката и записи за вход/изход от профила (включително списък на активните сесии, който виждаш в профила си).`,
         `Запис за съгласието ти: кои категории бисквитки си приел или отказал, кога и срещу коя версия на политиката.`,
         `Предпочитания (само със съгласие): кои марки, модели и горива разглеждаш, в бисквитка на твоето устройство със срок 90 дни.`]],
      ["3. Откъде получаваме данните",
        [`Повечето данни получаваме директно от теб. В някои случаи получаваме данни, свързани с теб, и от трети страни:`,
         `от превозвача и услугата за проследяване на контейнери — събития по пратката, статус на контейнера и товарителницата;`,
         `от Google — имейл, име и профилна снимка, само ако избереш вход с Google;`,
         `от Stripe — резултата, статуса и идентификатора на плащането ти (но не и данните на картата);`,
         `от нашите логистични, митнически и корейски партньори — данни, необходими за конкретната ти поръчка и превоз.`,
         `Категориите на тези данни и правните основания за обработването им са същите като описаните в тази политика.`]],
      ["4. Задължителност на предоставянето на данните",
        [`Предоставянето на част от данните е необходимо, за да сключим и изпълним договора с теб или за да спазим закона:`,
         `без имейл и парола не можем да създадем и поддържаме профил;`,
         `без име, адрес и телефон не можем да обработим поръчка, внос и доставка;`,
         `без данните за плащане Stripe не може да приеме депозит или плащане.`,
         `Ако не предоставиш тези данни, няма да можем да ти предоставим съответната услуга. Останалите данни (напр. предпочитания и незадължителни полета) са изцяло доброволни и отказът им не засяга достъпа ти до основната услуга.`]],
      ["5. Защо и на какво правно основание обработваме данните",
        [`Изпълнение на договор или преддоговорни действия (чл. 6, § 1, б. „б“ GDPR): регистрация и поддръжка на профила, обработка на запитване, поръчка, депозит, внос, проследяване и доставка.`,
         `Законово задължение (чл. 6, § 1, б. „в“): счетоводна и данъчна отчетност, митнически документи, задължения по Закона за мерките срещу изпирането на пари, когато са приложими.`,
         `Легитимен интерес (чл. 6, § 1, б. „е“): сигурност на сайта и предотвратяване на измами, поддържане на записи за защита при спор, техническа поддръжка и отстраняване на грешки. Преценили сме, че тези цели не накърняват неоправдано правата ти; можеш да поискаш обобщение на тази преценка на ${COMPANY.email} и да възразиш по всяко време (виж раздел 10).`,
         `Съгласие (чл. 6, § 1, б. „а“): бисквитки и подобни технологии, които не са строго необходими, персонализирани предложения, известия по имейл и push за спад в цената или нова кола по запазено търсене. Съгласието се оттегля по всяко време — от „Настройки за бисквитки“ във футъра или от профила — без това да засяга законосъобразността на обработването преди оттеглянето.`]],
      ["6. Бисквитки и подобни технологии",
        [`Не записваме и не четем нищо на твоето устройство извън строго необходимото, преди да си дал изрично съгласие за съответната категория. Отказът е толкова лесен, колкото приемането, и превключвателите са изключени по подразбиране.`,
         `Пълният списък с имена, цели и срокове е в Политиката за бисквитките. Ако някога включим статистика от трета страна (Google Analytics 4), тя ще се зарежда само след съгласие за категория „Статистика“, с отказано по подразбиране съгласие (Consent Mode) и без рекламни сигнали.`]],
      ["7. С кого споделяме данните",
        [`Споделяме данни само доколкото е необходимо и със следните категории получатели:`,
         `Хостинг и инфраструктура: Hetzner Online GmbH, сървъри в Германия (обработващ лични данни).`,
         `Имейли: Resend (транзакционни съобщения — потвърждения, известия, отговори на запитвания).`,
         `Плащания: Stripe Payments Europe — самостоятелен администратор за данните на картата ти; ние получаваме само резултата от плащането.`,
         `Превод на текстовете от обявите: Anthropic и Google. Изпращат се само данни от обявата (марка, модел, описание от търговеца), никога твои лични данни.`,
         `Вход с Google: Google Ireland Ltd, само ако сам избереш този начин на вход. Получаваме имейл, име и профилна снимка.`,
         `Проследяване на пратки: превозвачът (напр. Maersk) и услугата за проследяване на контейнери, с която работим.`,
         `Логистика и внос: спедитори, превозвачи, митнически агенти, пристанищни оператори и корейските ни партньори, доколкото е нужно за твоята поръчка.`,
         `Професионални консултанти: счетоводител, а при нужда адвокат или одитор, обвързани с поверителност.`,
         `Държавни органи, когато законът го изисква.`,
         `С всеки доставчик, който обработва лични данни от наше име, сме сключили договор по чл. 28 GDPR, който го задължава да обработва данните само по наши инструкции, да гарантира поверителност и подходящи технически и организационни мерки и да заличи или върне данните при прекратяване на услугата. Самостоятелните администратори (напр. Stripe, Google) обработват данните ти по собствените си политики за поверителност.`,
         `Не продаваме лични данни и не ги предоставяме на рекламни мрежи.`]],
      ["8. Предаване извън ЕС/ЕИП",
        [`Част от доставчиците ни (Anthropic, Google, Stripe) и партньорите ни в Южна Корея се намират извън ЕИП. Предаването се извършва въз основа на решение на Европейската комисия за адекватно ниво на защита, когато за съответния получател има такова (включително рамката EU–US Data Privacy Framework), а в останалите случаи — въз основа на стандартни договорни клаузи по чл. 46, § 2, б. „в“ GDPR, придружени при нужда от допълнителни мерки.`,
         `Към корейските партньори и превозвачите изпращаме само минимума, нужен за конкретната покупка и превоз. Данните за превод не съдържат лична информация. Копие от приложимите гаранции можеш да поискаш на ${COMPANY.email}.`]],
      ["9. Колко дълго пазим данните",
        [`Счетоводни регистри и финансови отчети: 10 години, считано от 1 януари на годината, следваща годината на съставянето им. Останалите счетоводни и данъчни документи се пазят за сроковете по Закона за счетоводството и ДОПК според вида им.`,
         `Профил и адрес: докато поддържаш профила. При изтриване премахваме профила, адреса, сесиите, passkeys и двуфакторните тайни; остават само документите, които сме длъжни да пазим по закон.`,
         `Запитвания без сключена сделка: до 2 години от последната кореспонденция.`,
         `Сесии: до 30 дни от последната активност. Технически записи и логове: до 90 дни.`,
         `Запис за съгласие: 12 месеца (след което питаме отново) и до 3 години като доказателство, че съгласието е било дадено или отказано.`,
         `Бисквитка с предпочитания: 90 дни от последната активност; изтриването на бисквитките я премахва веднага.`]],
      ["10. Твоите права",
        [`Спрямо личните си данни имаш право на: достъп и копие от данните (чл. 15); коригиране (чл. 16); изтриване (чл. 17); ограничаване на обработването (чл. 18); преносимост в машинно четим формат (чл. 20); възражение срещу обработване на основание легитимен интерес (чл. 21, § 1); оттегляне на съгласие по всяко време — от „Настройки за бисквитки“ във футъра, съответните превключватели в профила или имейл до нас.`,
         `Ако някога изпращаме съобщения с цел директен маркетинг, имаш безусловно право да възразиш по всяко време и без да посочваш причина; след възражение спираме тези съобщения (чл. 21, § 2–3).`,
         `Заявките са безплатни; изпрати ги на ${COMPANY.email}. Може да поискаме допълнителна информация, за да се уверим, че заявката е от теб. Отговаряме в сроковете по раздел 1.`,
         `Имаш право на жалба до Комисията за защита на личните данни, гр. София 1592, бул. „Проф. Цветан Лазаров“ № 2, kzld.bg. Ако си в Румъния — до ANSPDCP (dataprotection.ro), или до надзорния орган по местоживеенето ти.`]],
      ["11. Автоматизирано вземане на решения и профилиране",
        [`Класирането „Подходящи“ и предложенията за автомобили се основават на общи критерии за търсене и на предпочитанията, които сам си посочил или разгледал. Те са само помощно средство при търсенето, не пораждат правни последици за теб и не те засягат по подобен съществен начин, поради което не представляват автоматизирано вземане на решения или профилиране по смисъла на чл. 22 GDPR. Не влияят на цената, която виждаш, нито на условията, които получаваш.`]],
      ["12. Деца",
        [`Услугата е предназначена за лица над 18 години. Не събираме съзнателно данни на деца. Ако разберем, че сме получили такива, ги изтриваме.`]],
      ["13. Сигурност",
        [`Целият трафик е криптиран (HTTPS). Паролите се съхраняват само като Argon2id хеш. Сесиите са сървърни, с HttpOnly бисквитка, и могат да се прекратят от профила ти по всяко време; предлагаме двуфакторна защита и passkeys. Достъпът до данните е ограничен до лицата, които го изискват за работата си. Правим редовни резервни копия и водим одитен дневник на административните действия.`,
         `При нарушение на сигурността, което води до висок риск за правата ти, ще те уведомим и ще уведомим КЗЛД в сроковете по чл. 33–34 GDPR.`]],
      ["14. Промени в политиката",
        [`Всяка съществена промяна се отразява в номера на версията и датата на актуализация и — когато засяга съгласието ти — в нова версия, при която банерът за съгласие ще те попита отново.`]],
      ["Бележка",
        [`Този текст е изготвен добросъвестно и подробно, но не замества юридическа консултация. Преди да разчиташ на него търговски, дай го за преглед на адвокат.`]],
    ],
    PRIVACY_STAMP.bg
  ),
  cookies: doc(
    "Политика за бисквитките",
    `Нищо, което не е строго необходимо, не се записва и не се чете от твоето устройство, преди да си дал изрично съгласие. По-долу е всяка бисквитка и всяко подобно средство, което използваме, за какво служи и колко живее.`,
    [
      ["Как работи съгласието",
        [`При първото посещение показваме банер с три равнопоставени избора: „Отказвам всички“, „Настройки“ и „Приемам всички“. Превключвателите за незадължителните категории са изключени по подразбиране.`,
         `Изборът се записва като запис — категории, дата и версия на политиката — за 12 месеца. След това питаме отново, както и при съществена промяна на тази политика.`,
         `Можеш да промениш или оттеглиш избора си по всяко време от „Настройки за бисквитки“ във футъра на всяка страница. При отказ съответните бисквитки се изтриват веднага.`]],
      ["Строго необходими (без съгласие)",
        [`encar_session — държи те влязъл в профила. HttpOnly, срок 30 дни; изтрива се при изход.`,
         `ab_consent — самият твой избор за бисквитките. Срок 12 месеца. Пази и отказ, затова е необходима.`,
         `Локално в браузъра (localStorage): избраният език, валута и тема (светла/тъмна), а за посетители без профил — запазените коли и търсения, които сам си запазил, докато не ги изтриеш.`,
         `Технически кеш на текстовете и страниците, за да не се презареждат при всяко отваряне. Не съдържа лични данни и не идентифицира устройството.`,
         `Тези средства са необходими, за да работи сайтът и услугата, която сам поиска, затова законът не изисква съгласие за тях.`]],
      ["Персонализация (със съгласие)",
        [`ab_taste — кои марки, модели и горива разглеждаш, за да подредим подходящите автомобили. Срок 90 дни.`,
         `ab_vid — случаен идентификатор на браузъра, свързан със същия профил на предпочитания. Не съдържа име или имейл. Срок 90 дни.`,
         `ab_track — номерата, които вече си проверявал в „Проследи автомобила“, за да не ги въвеждаш отново. Срок 90 дни.`,
         `Ако откажеш, сайтът работи напълно — просто не подреждаме предложенията по твоите интереси.`]],
      ["Статистика (със съгласие)",
        [`Брояч на отваряния на обява: изпраща се към нашия сървър, за да знаем кои автомобили се търсят. Не записва бисквитка на устройството ти и не се свързва с профил.`,
         `Ако в бъдеще включим Google Analytics 4, той ще се зарежда само след съгласие за тази категория, с отказани по подразбиране разрешения (Google Consent Mode), с анонимизиран IP и без рекламни сигнали. Днес не е активен и никакъв скрипт на Google не се зарежда.`]],
      ["Маркетинг и реклама",
        [`Не използваме. Няма рекламни мрежи, няма ретаргетинг, няма пиксели на трети страни и няма продажба или обмен на данни с рекламодатели.`]],
      ["Изтриване от браузъра",
        [`Освен от нашите настройки можеш да изтриеш или блокираш бисквитките и от настройките на браузъра си. Блокирането на строго необходимите може да наруши входа в профила.`]],
      ["Въпроси",
        [`Пиши на ${COMPANY.email}. Как обработваме личните данни е описано в Политиката за поверителност.`]],
    ]
  ),
  contact: doc(
    "Контакт и данни за фирмата",
    `Сайтът се управлява от ${COMPANY.name}.`,
    [
      ["Фирмени данни",
        [`Наименование: ${COMPANY.name}`, `ЕИК: ${COMPANY.eik}`, `Адрес: ${COMPANY.address}`,
         `Телефон: ${COMPANY.phone}`, `Държава на регистрация: България`]],
      ["Връзка с нас",
        [`Имейл: ${COMPANY.email}`, `Отговаряме в рамките на два работни дни.`]],
      ["Жалби",
        [`Ако не сме решили въпроса ти, можеш да се обърнеш към Комисията за защита на потребителите.`]],
    ]
  ),
};

const RO = {
  terms: doc(
    "Termeni și condiții",
    `Acești termeni reglementează folosirea site-ului ${COMPANY.site} și comanda unei mașini prin ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
    [
      ["Ce facem",
        [`Afișăm mașini scoase la vânzare în Coreea de Sud, traduse în bulgară, română și engleză.`,
         `Prețul afișat este prețul final estimat până la adresa ta: mașina, transportul maritim, taxele vamale și TVA, dacă pagina anunțului nu spune altfel.`]],
      ["Anunțurile nu ne aparțin",
        [`Datele și fotografiile provin din piața coreeană și se actualizează periodic. O mașină poate fi vândută înainte să primim date noi.`,
         `De aceea un anunț este o invitație la cerere, nu o ofertă obligatorie. Prețul obligatoriu îl primești în confirmarea noastră scrisă.`]],
      ["Comandă și plată",
        [`După cerere confirmăm disponibilitatea, prețul final și termenul, apoi emitem documentul de plată. Contractul se încheie când confirmăm comanda în scris.`,
         `Plata se face prin transfer bancar către ${COMPANY.name}. Nu acceptăm numerar pentru mașini.`]],
      ["Termene și livrare",
        [`Termenul orientativ de la comanda confirmată până la livrare este de 6-10 săptămâni și depinde de orarele navelor și de procedurile portuare și vamale.`,
         `Datele din „Urmărește mașina” sunt estimări. Ultimul pas — livrarea la adresa ta — se calculează la aproximativ șapte zile după sosirea în portul european.`]],
      ["Starea mașinii",
        [`Mașinile sunt second-hand. Afișăm raportul de inspecție și istoricul, în măsura în care sursa le pune la dispoziție.`,
         `O mașină folosită poate avea uzură care nu apare în documente. Dacă ai dubii, cere o verificare suplimentară înainte de comandă.`]],
      ["Dreptul de retragere",
        [`Dacă ești consumator, îți păstrezi drepturile legale, inclusiv dreptul de retragere atunci când se aplică tranzacției tale.`,
         `O mașină adusă la cererea ta individuală expresă poate intra în excepțiile de la dreptul de retragere. Îți spunem ce se aplică înainte de plată.`]],
      ["Răspundere",
        [`Nu răspundem pentru întârzieri provocate de transportatori, porturi, vamă sau autorități, dar te informăm imediat ce le aflăm.`,
         `Nu răspundem pentru prejudicii indirecte, precum profit nerealizat sau costul închirierii altei mașini.`]],
      ["Litigii",
        [`Se aplică legea bulgară. Litigiile se soluționează de instanța bulgară competentă, dacă o normă imperativă de protecție a consumatorului nu prevede altfel.`,
         `Poți folosi și platforma europeană de soluționare online a litigiilor.`]],
      ["Contact",
        [`Scrie-ne la ${COMPANY.email}. Răspundem în două zile lucrătoare.`]],
    ]
  ),
  privacy: doc(
    "Politica de confidențialitate",
    `${COMPANY.name}, cod unic ${COMPANY.eik}, cu sediul social și adresa de administrare în ${COMPANY.address}, este operatorul datelor personale prelucrate prin ${COMPANY.site}. Această politică explică ce date colectăm, în baza cărui temei, de unde le primim, cu cine le împărtășim, cât timp le păstrăm și cum îți exerciți drepturile conform Regulamentului (UE) 2016/679 (GDPR) și legislației bulgare privind protecția datelor.`,
    [
      ["1. Cine răspunde pentru datele tale",
        [`Operator: ${COMPANY.name}, cod unic ${COMPANY.eik}.`,
         `Adresă: ${COMPANY.address}.`,
         `Contact pentru întrebări și cereri GDPR: ${COMPANY.email}; tel. ${COMPANY.phone}.`,
         `Nu avem obligația de a numi un responsabil cu protecția datelor și nu am numit unul. Cererile sunt tratate de administrator și primești răspuns în termen de o lună de la primirea lor. În cazul cererilor complexe sau numeroase, termenul poate fi prelungit cu încă două luni, iar te vom informa despre prelungire și motivele ei în prima lună.`]],
      ["2. Ce date prelucrăm",
        [`Cont: e-mail, nume (dacă îl completezi), parola — păstrată doar ca hash ireversibil (Argon2id) — și datele pentru autentificarea în doi pași sau passkey, dacă le-ai activat.`,
         `Livrare și facturare: nume, stradă, oraș, cod poștal, țară și telefon — numai dacă le introduci.`,
         `Cereri și corespondență: mesajul, e-mailul și telefonul pe care ni le trimiți, plus răspunsurile noastre.`,
         `Plăți și depozite: sumă, stare, dată și identificatorul plății. Datele cardului se introduc direct la Stripe — noi nu vedem și nu stocăm niciodată numărul cardului.`,
         `Transporturi: numerele de conosament și de container legate de comanda ta, evenimentele de la transportator și țara pentru ultimul pas al livrării.`,
         `Date tehnice: adresa IP, tipul de browser și dispozitiv, momentul cererii și înregistrările de autentificare (inclusiv lista sesiunilor active, pe care o vezi în cont).`,
         `Înregistrarea consimțământului tău: ce categorii de cookie-uri ai acceptat sau refuzat, când și față de ce versiune a politicii.`,
         `Preferințe (numai cu consimțământ): ce mărci, modele și combustibili deschizi, într-un cookie de pe dispozitivul tău, valabil 90 de zile.`]],
      ["3. De unde primim datele",
        [`Cele mai multe date le primim direct de la tine. În unele cazuri primim date legate de tine și de la terți:`,
         `de la transportator și de la serviciul de urmărire a containerelor — evenimentele transportului, starea containerului și a conosamentului;`,
         `de la Google — e-mail, nume și poza de profil, doar dacă alegi autentificarea cu Google;`,
         `de la Stripe — rezultatul, starea și identificatorul plății tale (dar nu datele cardului);`,
         `de la partenerii noștri logistici, vamali și coreeni — datele necesare pentru comanda și transportul tău.`,
         `Categoriile acestor date și temeiurile juridice ale prelucrării lor sunt aceleași cu cele descrise în această politică.`]],
      ["4. Caracterul obligatoriu al furnizării datelor",
        [`Furnizarea unei părți din date este necesară pentru a încheia și executa contractul cu tine sau pentru a respecta legea:`,
         `fără e-mail și parolă nu putem crea și menține un cont;`,
         `fără nume, adresă și telefon nu putem procesa comanda, importul și livrarea;`,
         `fără datele de plată, Stripe nu poate accepta un depozit sau o plată.`,
         `Dacă nu furnizezi aceste date, nu îți vom putea oferi serviciul respectiv. Restul datelor (de ex. preferințele și câmpurile opționale) sunt complet voluntare, iar refuzul lor nu afectează accesul tău la serviciul principal.`]],
      ["5. De ce și în baza cărui temei prelucrăm datele",
        [`Executarea contractului sau demersuri precontractuale (art. 6 alin. 1 lit. b GDPR): înregistrarea și administrarea contului, tratarea cererii, comanda, depozitul, importul, urmărirea și livrarea.`,
         `Obligație legală (art. 6 alin. 1 lit. c): contabilitate și fiscalitate, documente vamale, obligații privind prevenirea spălării banilor, când sunt aplicabile.`,
         `Interes legitim (art. 6 alin. 1 lit. f): securitatea site-ului și prevenirea fraudei, păstrarea dovezilor în caz de litigiu, mentenanță tehnică și remedierea erorilor. Am evaluat că aceste scopuri nu îți afectează în mod nejustificat drepturile; poți cere un rezumat al acestei evaluări la ${COMPANY.email} și te poți opune oricând (vezi secțiunea 10).`,
         `Consimțământ (art. 6 alin. 1 lit. a): cookie-uri și tehnologii similare care nu sunt strict necesare, recomandări personalizate, notificări prin e-mail și push pentru scăderi de preț sau o mașină nouă într-o căutare salvată. Consimțământul se retrage oricând — din „Setări cookie-uri” din footer sau din cont — fără a afecta legalitatea prelucrării de dinaintea retragerii.`]],
      ["6. Cookie-uri și tehnologii similare",
        [`Nu scriem și nu citim nimic pe dispozitivul tău în afara strictului necesar înainte să îți dai consimțământul explicit pentru categoria respectivă. Refuzul este la fel de simplu ca acceptarea, iar comutatoarele sunt dezactivate implicit.`,
         `Lista completă cu nume, scopuri și durate este în Politica de cookie-uri. Dacă vom activa vreodată statistici de la un terț (Google Analytics 4), acestea se vor încărca doar după consimțământ pentru categoria „Statistici”, cu permisiuni refuzate implicit (Consent Mode) și fără semnale publicitare.`]],
      ["7. Cu cine împărtășim datele",
        [`Împărtășim datele doar în măsura necesară și cu următoarele categorii de destinatari:`,
         `Găzduire și infrastructură: Hetzner Online GmbH, servere în Germania (persoană împuternicită).`,
         `E-mailuri: Resend (mesaje tranzacționale — confirmări, notificări, răspunsuri la cereri).`,
         `Plăți: Stripe Payments Europe — operator independent pentru datele cardului; noi primim doar rezultatul plății.`,
         `Traducerea textelor din anunțuri: Anthropic și Google. Se trimit doar date din anunț (marcă, model, descrierea dealerului), niciodată datele tale personale.`,
         `Autentificare cu Google: Google Ireland Ltd, doar dacă alegi tu această metodă. Primim e-mailul, numele și poza de profil.`,
         `Urmărirea transporturilor: transportatorul (de ex. Maersk) și serviciul de urmărire a containerelor cu care lucrăm.`,
         `Logistică și import: case de expediții, transportatori, agenți vamali, operatori portuari și partenerii noștri coreeni, cât este necesar pentru comanda ta.`,
         `Consultanți profesioniști: contabil și, la nevoie, avocat sau auditor, obligați la confidențialitate.`,
         `Autorități, când legea o cere.`,
         `Cu fiecare furnizor care prelucrează date personale în numele nostru am încheiat un contract conform art. 28 GDPR, care îl obligă să prelucreze datele numai după instrucțiunile noastre, să asigure confidențialitatea și măsuri tehnice și organizatorice adecvate și să șteargă sau să returneze datele la încetarea serviciului. Operatorii independenți (de ex. Stripe, Google) prelucrează datele tale conform propriilor politici de confidențialitate.`,
         `Nu vindem date personale și nu le oferim rețelelor de publicitate.`]],
      ["8. Transferuri în afara UE/SEE",
        [`Unii furnizori (Anthropic, Google, Stripe) și partenerii noștri din Coreea de Sud se află în afara SEE. Transferul are loc în baza unei decizii de adecvare a Comisiei Europene, când există una pentru destinatarul respectiv (inclusiv EU–US Data Privacy Framework), iar în celelalte cazuri în baza clauzelor contractuale standard conform art. 46 alin. 2 lit. c GDPR, însoțite la nevoie de măsuri suplimentare.`,
         `Către partenerii coreeni și transportatori trimitem doar minimul necesar pentru achiziția și transportul respectiv. Datele trimise pentru traducere nu conțin informații personale. O copie a garanțiilor aplicabile poate fi cerută la ${COMPANY.email}.`]],
      ["9. Cât timp păstrăm datele",
        [`Registre contabile și situații financiare: 10 ani, începând cu 1 ianuarie a anului următor celui în care au fost întocmite. Celelalte documente contabile și fiscale se păstrează pe termenele prevăzute de legislația bulgară, în funcție de tipul lor.`,
         `Cont și adresă: cât timp păstrezi contul. La ștergere eliminăm contul, adresa, sesiunile, passkeys și secretele de autentificare în doi pași; rămân doar documentele pe care legea ne obligă să le păstrăm.`,
         `Cereri fără tranzacție încheiată: până la 2 ani de la ultima corespondență.`,
         `Sesiuni: până la 30 de zile de la ultima activitate. Jurnale tehnice: până la 90 de zile.`,
         `Înregistrarea consimțământului: 12 luni (după care întrebăm din nou) și până la 3 ani ca dovadă că a fost dat sau refuzat.`,
         `Cookie-ul de preferințe: 90 de zile de la ultima activitate; ștergerea cookie-urilor îl elimină imediat.`]],
      ["10. Drepturile tale",
        [`În legătură cu datele tale personale ai dreptul la: acces și o copie a datelor (art. 15); rectificare (art. 16); ștergere (art. 17); restricționarea prelucrării (art. 18); portabilitate în format prelucrabil automat (art. 20); opoziție față de prelucrarea bazată pe interes legitim (art. 21 alin. 1); retragerea consimțământului oricând — din „Setări cookie-uri” din footer, comutatoarele din cont sau un e-mail către noi.`,
         `Dacă vom trimite vreodată mesaje de marketing direct, ai dreptul necondiționat de a te opune oricând și fără să indici un motiv; după opoziție oprim aceste mesaje (art. 21 alin. 2–3).`,
         `Cererile sunt gratuite; trimite-le la ${COMPANY.email}. Putem cere informații suplimentare pentru a ne asigura că cererea vine de la tine. Răspundem în termenele din secțiunea 1.`,
         `Ai dreptul de a depune plângere la ANSPDCP (B-dul G-ral. Gheorghe Magheru 28-30, București, dataprotection.ro), la Comisia bulgară pentru protecția datelor personale (Sofia 1592, bd. „Prof. Tsvetan Lazarov” nr. 2, kzld.bg) sau la autoritatea de supraveghere din țara ta de reședință.`]],
      ["11. Decizii automatizate și profilare",
        [`Clasamentul „Potrivite” și recomandările de mașini se bazează pe criterii generale de căutare și pe preferințele pe care le-ai indicat sau consultat tu. Sunt doar un ajutor la căutare, nu produc efecte juridice asupra ta și nu te afectează în mod similar semnificativ, deci nu constituie decizii automatizate sau profilare în sensul art. 22 GDPR. Nu influențează prețul afișat, nici condițiile pe care le primești.`]],
      ["12. Copii",
        [`Serviciul este destinat persoanelor peste 18 ani. Nu colectăm cu bună știință date ale copiilor. Dacă aflăm că am primit astfel de date, le ștergem.`]],
      ["13. Securitate",
        [`Tot traficul este criptat (HTTPS). Parolele sunt păstrate doar ca hash Argon2id. Sesiunile sunt pe server, cu cookie HttpOnly, și pot fi închise oricând din contul tău; oferim autentificare în doi pași și passkeys. Accesul la date este limitat la persoanele care au nevoie de el pentru munca lor. Facem copii de siguranță periodice și păstrăm un jurnal de audit al acțiunilor administrative.`,
         `În caz de încălcare a securității care duce la un risc ridicat pentru drepturile tale, te vom informa pe tine și autoritatea de supraveghere în termenele din art. 33–34 GDPR.`]],
      ["14. Modificări ale politicii",
        [`Orice modificare importantă se reflectă în numărul versiunii și în data actualizării și — când îți afectează consimțământul — într-o versiune nouă, caz în care bannerul de consimțământ te va întreba din nou.`]],
      ["Notă",
        [`Textul este redactat cu bună-credință și în detaliu, dar nu înlocuiește consultanța juridică. Cere avizul unui avocat înainte să te bazezi comercial pe el.`]],
    ],
    PRIVACY_STAMP.ro
  ),
  cookies: doc(
    "Politica de cookie-uri",
    `Nimic care nu este strict necesar nu se scrie și nu se citește de pe dispozitivul tău înainte să îți dai consimțământul explicit. Mai jos sunt toate cookie-urile și mijloacele similare pe care le folosim, la ce servesc și cât trăiesc.`,
    [
      ["Cum funcționează consimțământul",
        [`La prima vizită afișăm un banner cu trei opțiuni egale: „Refuz toate”, „Setări” și „Accept toate”. Comutatoarele categoriilor opționale sunt dezactivate implicit.`,
         `Alegerea se salvează ca înregistrare — categorii, dată și versiunea politicii — pentru 12 luni. Apoi întrebăm din nou, la fel ca la o modificare importantă a acestei politici.`,
         `Poți schimba sau retrage alegerea oricând din „Setări cookie-uri”, în footerul fiecărei pagini. La refuz, cookie-urile respective se șterg imediat.`]],
      ["Strict necesare (fără consimțământ)",
        [`encar_session — te menține autentificat. HttpOnly, 30 de zile; se șterge la deconectare.`,
         `ab_consent — chiar alegerea ta privind cookie-urile. 12 luni. Păstrează și un refuz, de aceea este necesar.`,
         `Local în browser (localStorage): limba, moneda și tema aleasă, iar pentru vizitatorii fără cont — mașinile și căutările salvate de tine, până le ștergi.`,
         `Cache tehnic al textelor și paginilor, ca să nu se reîncarce la fiecare deschidere. Nu conține date personale și nu identifică dispozitivul.`,
         `Aceste mijloace sunt necesare pentru funcționarea site-ului și a serviciului cerut de tine, deci legea nu impune consimțământ pentru ele.`]],
      ["Personalizare (cu consimțământ)",
        [`ab_taste — ce mărci, modele și combustibili deschizi, ca să ordonăm mașinile potrivite. 90 de zile.`,
         `ab_vid — un identificator aleatoriu al browserului, legat de același profil de preferințe. Nu conține nume sau e-mail. 90 de zile.`,
         `ab_track — numerele verificate deja în „Urmărește mașina”, ca să nu le reintroduci. 90 de zile.`,
         `Dacă refuzi, site-ul funcționează complet — doar nu ordonăm recomandările după interesele tale.`]],
      ["Statistici (cu consimțământ)",
        [`Contorul de deschideri ale unui anunț: se trimite către serverul nostru, ca să știm ce mașini se caută. Nu scrie un cookie pe dispozitivul tău și nu se leagă de cont.`,
         `Dacă vom activa în viitor Google Analytics 4, se va încărca doar după consimțământ pentru această categorie, cu permisiuni refuzate implicit (Google Consent Mode), IP anonimizat și fără semnale publicitare. Astăzi nu este activ și niciun script Google nu se încarcă.`]],
      ["Marketing și publicitate",
        [`Nu folosim. Fără rețele de publicitate, fără retargeting, fără pixeli ai terților și fără vânzarea sau schimbul de date cu advertiseri.`]],
      ["Ștergerea din browser",
        [`În plus față de setările noastre, poți șterge sau bloca cookie-urile din browserul tău. Blocarea celor strict necesare poate împiedica autentificarea.`]],
      ["Întrebări",
        [`Scrie la ${COMPANY.email}. Modul în care prelucrăm datele personale este descris în Politica de confidențialitate.`]],
    ]
  ),
  contact: doc(
    "Contact și date despre firmă",
    `Site-ul este administrat de ${COMPANY.name}.`,
    [
      ["Date despre firmă",
        [`Denumire: ${COMPANY.name}`, `Cod unic: ${COMPANY.eik}`, `Adresă: ${COMPANY.address}`,
         `Telefon: ${COMPANY.phone}`, `Țara de înregistrare: Bulgaria`]],
      ["Contact",
        [`E-mail: ${COMPANY.email}`, `Răspundem în două zile lucrătoare.`]],
      ["Reclamații",
        [`Dacă nu am rezolvat problema, te poți adresa autorității de protecție a consumatorului.`]],
    ]
  ),
};

const EN = {
  terms: doc(
    "Terms of service",
    `These terms cover the use of ${COMPANY.site} and ordering a car through ${COMPANY.name}, company number ${COMPANY.eik}.`,
    [
      ["What we do",
        [`We show cars offered for sale in South Korea, translated into Bulgarian, Romanian and English.`,
         `The price you see is the estimated final price to your address: the car, sea freight, customs duty and VAT, unless the listing page says otherwise.`]],
      ["The listings are not ours",
        [`Data and photos come from the Korean market and are refreshed periodically. A car can be sold before we receive updated data.`,
         `A listing is therefore an invitation to enquire, not a binding offer. A binding price comes in our written confirmation.`]],
      ["Ordering and payment",
        [`After your enquiry we confirm availability, the final price and the lead time, then issue the payment document. The contract is formed when we confirm your order in writing.`,
         `Payment is by bank transfer to ${COMPANY.name}. We do not accept cash for vehicles.`]],
      ["Lead times and delivery",
        [`From a confirmed order to delivery usually takes 6 to 10 weeks, depending on sailing schedules and on port and customs procedures.`,
         `Dates on the "Track my vehicle" page are estimates. The final step — delivery to your address — is calculated as roughly seven days after arrival at the European port.`]],
      ["Condition of the car",
        [`The cars are used. We show the inspection report and the history as far as the source makes them available.`,
         `A used car can have wear that the paperwork does not record. If in doubt, ask for an extra inspection before you order.`]],
      ["Right of withdrawal",
        [`If you are a consumer, you keep your statutory rights, including the right of withdrawal where it applies to your transaction.`,
         `A car imported on your express individual instruction may fall within the exceptions to that right. We will tell you which applies before you pay.`]],
      ["Liability",
        [`We are not liable for delays caused by carriers, ports, customs or authorities outside our control, but we always pass them on as soon as we learn of them.`,
         `We are not liable for indirect losses such as lost profit or the cost of hiring another car.`]],
      ["Disputes",
        [`Bulgarian law applies. Disputes go to the competent Bulgarian court, unless a mandatory consumer rule says otherwise.`,
         `You may also use the European Commission's online dispute resolution platform.`]],
      ["Contact",
        [`Write to ${COMPANY.email}. We answer within two working days.`]],
    ]
  ),
  privacy: doc(
    "Privacy policy",
    `${COMPANY.name}, company number ${COMPANY.eik}, with its registered seat and management address at ${COMPANY.address}, is the controller of the personal data processed through ${COMPANY.site}. This policy explains what data we collect, on what basis, where we get it from, who we share it with, how long we keep it and how you exercise your rights under Regulation (EU) 2016/679 (GDPR) and Bulgarian data protection law.`,
    [
      ["1. Who is responsible for your data",
        [`Controller: ${COMPANY.name}, company number ${COMPANY.eik}.`,
         `Address: ${COMPANY.address}.`,
         `Contact for questions and GDPR requests: ${COMPANY.email}; phone ${COMPANY.phone}.`,
         `We are not required to appoint a data protection officer and have not appointed one. Requests are handled by the manager and answered within one month of receipt. For complex or numerous requests the deadline may be extended by a further two months, and we will tell you about the extension and the reasons for it within the first month.`]],
      ["2. What data we process",
        [`Account: email, name (if you fill it in), password — kept only as an irreversible hash (Argon2id) — and two-factor or passkey data if you have switched either on.`,
         `Delivery and invoicing: name, street, city, post code, country and phone — only if you enter them.`,
         `Enquiries and correspondence: the message, email and phone you send us, and our replies.`,
         `Payments and deposits: amount, status, date and the payment reference. Your card details are entered directly with Stripe — we never see or store a card number.`,
         `Shipments: the bill of lading and container numbers tied to your order, the carrier's events, and the country for the final delivery step.`,
         `Technical data: IP address, browser and device type, request time and sign-in records (including the list of active sessions you can see in your account).`,
         `Your consent record: which cookie categories you accepted or refused, when, and against which version of this policy.`,
         `Preferences (only with consent): which makes, models and fuels you browse, in a cookie on your own device for 90 days.`]],
      ["3. Where we get the data from",
        [`Most data comes directly from you. In some cases we also receive data relating to you from third parties:`,
         `from the carrier and the container tracking service — shipment events, container and bill of lading status;`,
         `from Google — email, name and profile picture, only if you choose to sign in with Google;`,
         `from Stripe — the result, status and reference of your payment (but not your card details);`,
         `from our logistics, customs and Korean partners — the data needed for your particular order and shipment.`,
         `The categories of that data and the legal bases for processing it are the same as those described in this policy.`]],
      ["4. Whether providing the data is obligatory",
        [`Providing some of the data is necessary in order to enter into and perform our contract with you, or to comply with the law:`,
         `without an email and a password we cannot create and maintain an account;`,
         `without a name, address and phone we cannot process an order, the import and delivery;`,
         `without payment details Stripe cannot accept a deposit or a payment.`,
         `If you do not provide that data we will not be able to provide you with the service in question. All other data (for example preferences and optional fields) is entirely voluntary, and refusing it does not affect your access to the main service.`]],
      ["5. Why, and on what legal basis, we process the data",
        [`Performance of a contract or steps before it (Art. 6(1)(b) GDPR): registering and maintaining your account, handling an enquiry, the order, the deposit, the import, tracking and delivery.`,
         `Legal obligation (Art. 6(1)(c)): accounting and tax records, customs paperwork, anti-money-laundering duties where they apply.`,
         `Legitimate interests (Art. 6(1)(f)): site security and fraud prevention, keeping records to defend ourselves in a dispute, technical maintenance and fixing faults. We have assessed that these purposes do not unduly override your rights; you can ask for a summary of that assessment at ${COMPANY.email} and object at any time (see section 10).`,
         `Consent (Art. 6(1)(a)): cookies and similar technologies that are not strictly necessary, personalised suggestions, and email or push alerts for a price drop or a new car matching a saved search. Consent can be withdrawn at any time — from "Cookie settings" in the footer or from your account — without affecting the lawfulness of processing before withdrawal.`]],
      ["6. Cookies and similar technologies",
        [`We write nothing to, and read nothing from, your device beyond the strictly necessary before you have given explicit consent for that category. Refusing is as easy as accepting, and the toggles start switched off.`,
         `The full list of names, purposes and lifetimes is in the Cookie policy. If we ever enable third-party statistics (Google Analytics 4) it will load only after consent to the "Statistics" category, with consent denied by default (Consent Mode) and with no advertising signals.`]],
      ["7. Who we share the data with",
        [`We share data only as far as necessary, and with the following categories of recipient:`,
         `Hosting and infrastructure: Hetzner Online GmbH, servers in Germany (processor).`,
         `Email: Resend (transactional messages — confirmations, alerts, replies to enquiries).`,
         `Payments: Stripe Payments Europe — an independent controller for your card data; we receive only the outcome of the payment.`,
         `Translation of listing text: Anthropic and Google. Only listing data is sent (make, model, the dealer's description), never your personal data.`,
         `Google sign-in: Google Ireland Ltd, only if you choose that way in. We receive your email, name and profile picture.`,
         `Shipment tracking: the carrier (e.g. Maersk) and the container tracking service we work with.`,
         `Logistics and import: freight forwarders, carriers, customs agents, port operators and our Korean partners, as far as your order requires.`,
         `Professional advisers: our accountant and, where needed, a lawyer or auditor, all bound by confidentiality.`,
         `Public authorities, where the law requires it.`,
         `With every provider that processes personal data on our behalf we have concluded a contract under Art. 28 GDPR obliging it to process the data only on our instructions, to guarantee confidentiality and appropriate technical and organisational measures, and to delete or return the data when the service ends. Independent controllers (e.g. Stripe, Google) process your data under their own privacy policies.`,
         `We do not sell personal data and we do not pass it to advertising networks.`]],
      ["8. Transfers outside the EU/EEA",
        [`Some of our providers (Anthropic, Google, Stripe) and our partners in South Korea are outside the EEA. Transfers take place on the basis of a European Commission adequacy decision where one exists for that recipient (including the EU–US Data Privacy Framework), and otherwise on the basis of Standard Contractual Clauses under Art. 46(2)(c) GDPR, accompanied by supplementary measures where needed.`,
         `To Korean partners and carriers we send only the minimum a specific purchase and shipment requires. Data sent for translation contains no personal information. You can request a copy of the applicable safeguards at ${COMPANY.email}.`]],
      ["9. How long we keep the data",
        [`Accounting ledgers and financial statements: 10 years, counted from 1 January of the year following the year in which they were drawn up. Other accounting and tax documents are kept for the periods set by Bulgarian accounting and tax law according to their type.`,
         `Account and address: for as long as you keep the account. On deletion we remove the account, the address, sessions, passkeys and two-factor secrets; only documents we are legally obliged to keep remain.`,
         `Enquiries that did not lead to a transaction: up to 2 years from the last correspondence.`,
         `Sessions: up to 30 days from the last activity. Technical records and logs: up to 90 days.`,
         `Consent record: 12 months (after which we ask again) and up to 3 years as proof that consent was given or refused.`,
         `Preference cookie: 90 days from the last activity; clearing your cookies removes it immediately.`]],
      ["10. Your rights",
        [`In relation to your personal data you have the right to: access and a copy of the data (Art. 15); rectification (Art. 16); erasure (Art. 17); restriction of processing (Art. 18); portability in a machine-readable format (Art. 20); objection to processing based on legitimate interests (Art. 21(1)); and withdrawal of consent at any time — from "Cookie settings" in the footer, the relevant toggles in your account, or an email to us.`,
         `If we ever send direct marketing messages, you have an unconditional right to object at any time and without giving a reason; after an objection we stop those messages (Art. 21(2)-(3)).`,
         `Requests are free of charge; send them to ${COMPANY.email}. We may ask for further information to satisfy ourselves that the request comes from you. We reply within the deadlines in section 1.`,
         `You have the right to complain to the Commission for Personal Data Protection, 2 Prof. Tsvetan Lazarov Blvd, Sofia 1592, kzld.bg. If you are in Romania — to ANSPDCP (dataprotection.ro), or to the supervisory authority where you live.`]],
      ["11. Automated decision-making and profiling",
        [`The "Relevant" ranking and the car suggestions are based on general search criteria and on the preferences you have entered or browsed yourself. They are only an aid to searching, produce no legal effects for you and do not similarly significantly affect you, so they do not amount to automated decision-making or profiling within the meaning of Art. 22 GDPR. They do not change the price you see or the terms you are offered.`]],
      ["12. Children",
        [`The service is intended for people over 18. We do not knowingly collect children's data. If we learn that we have received any, we delete it.`]],
      ["13. Security",
        [`All traffic is encrypted (HTTPS). Passwords are stored only as an Argon2id hash. Sessions are server-side behind an HttpOnly cookie and can be revoked from your account at any time; we offer two-factor authentication and passkeys. Access to data is limited to the people who need it for their work. We take regular backups and keep an audit log of administrative actions.`,
         `In the event of a security breach that leads to a high risk to your rights, we will notify you and the Commission for Personal Data Protection within the deadlines in Art. 33-34 GDPR.`]],
      ["14. Changes to this policy",
        [`Every material change is reflected in the version number and the update date and — where it affects your consent — in a new version, in which case the consent banner will ask you again.`]],
      ["Note",
        [`This text was drafted in good faith and in detail, but it does not replace legal advice. Have a lawyer review it before you rely on it commercially.`]],
    ],
    PRIVACY_STAMP.en
  ),
  cookies: doc(
    "Cookie policy",
    `Nothing that is not strictly necessary is written to or read from your device before you have given explicit consent. Below is every cookie and similar means we use, what it is for and how long it lives.`,
    [
      ["How consent works",
        [`On your first visit we show a banner with three equal choices: "Reject all", "Settings" and "Accept all". The toggles for the optional categories start switched off.`,
         `Your choice is stored as a record — categories, date and policy version — for 12 months. After that we ask again, as we do whenever this policy changes materially.`,
         `You can change or withdraw your choice at any time from "Cookie settings" in the footer of every page. On refusal the relevant cookies are deleted straight away.`]],
      ["Strictly necessary (no consent needed)",
        [`encar_session — keeps you signed in. HttpOnly, 30 days; deleted when you sign out.`,
         `ab_consent — your cookie choice itself. 12 months. It stores a refusal too, which is why it is necessary.`,
         `In your browser (localStorage): your chosen language, currency and light/dark theme, and for visitors without an account the cars and searches you saved yourself, until you delete them.`,
         `A technical cache of page copy so it is not re-fetched on every visit. It holds no personal data and identifies no device.`,
         `These are needed to run the site and the service you asked for, so the law does not require consent for them.`]],
      ["Personalisation (with consent)",
        [`ab_taste — which makes, models and fuels you browse, so we can order the cars that suit you. 90 days.`,
         `ab_vid — a random browser identifier tied to that same preference profile. It carries no name or email. 90 days.`,
         `ab_track — the references you have already looked up on Track my vehicle, so you do not retype them. 90 days.`,
         `If you refuse, the site still works fully — we simply do not order suggestions around your interests.`]],
      ["Statistics (with consent)",
        [`Listing view counter: sent to our own server so we know which cars people are looking for. It writes no cookie on your device and is not linked to an account.`,
         `If we enable Google Analytics 4 in future it will load only after consent to this category, with Google Consent Mode defaults denied, IP anonymisation on and no advertising signals. It is not active today and no Google script is loaded.`]],
      ["Marketing and advertising",
        [`We use none. No ad networks, no retargeting, no third-party pixels, and no selling or swapping of data with advertisers.`]],
      ["Clearing them in your browser",
        [`Besides our own settings you can delete or block cookies in your browser. Blocking the strictly necessary ones may stop you signing in.`]],
      ["Questions",
        [`Write to ${COMPANY.email}. How we handle personal data is set out in the Privacy policy.`]],
    ]
  ),
  contact: doc(
    "Contact and company details",
    `This site is operated by ${COMPANY.name}.`,
    [
      ["Company details",
        [`Name: ${COMPANY.name}`, `Company number: ${COMPANY.eik}`, `Address: ${COMPANY.address}`,
         `Phone: ${COMPANY.phone}`, `Country of registration: Bulgaria`]],
      ["Reach us",
        [`Email: ${COMPANY.email}`, `We answer within two working days.`]],
      ["Complaints",
        [`If we have not resolved your issue, you can turn to the Bulgarian consumer protection commission.`]],
    ]
  ),
};

return { bg: BG, ro: RO, en: EN };
}

let cache = null;
let cacheKey = "";

function docs() {
  const key = JSON.stringify(COMPANY);
  if (!cache || cacheKey !== key) {
    cache = build();
    cacheKey = key;
  }
  return cache;
}

export function legalDoc(lang, slug) {
  const DOCS = docs();
  const table = DOCS[lang] || DOCS.bg;
  return table[slug] || table.terms;
}
